export * from './types';
export * from './composables/useWindowManager';
export * from './composables/useDockPhysics';
export * from './composables/useSystemAudio';

export { default as MacWindow } from './components/MacWindow.vue';
export { default as MacAppIcon } from './components/MacAppIcon.vue';
export { default as MacDock } from './components/MacDock.vue';
export { default as MacMenubar } from './components/MacMenubar.vue';
export { default as MacTrafficLights } from './components/MacTrafficLights.vue';
export { default as MacSplitView } from './components/MacSplitView.vue';
export { default as MacSegmented } from './components/MacSegmented.vue';
export { default as MacToggle } from './components/MacToggle.vue';
export { default as MacSheet } from './components/MacSheet.vue';
export { default as MacDraftGuard } from './components/MacDraftGuard.vue';
export { default as MacTable } from './components/MacTable.vue';
export { default as MacSpotlight } from './components/MacSpotlight.vue';
export { default as MacAboutModal } from './components/MacAboutModal.vue';
export { default as MacIconBadge } from './components/MacIconBadge.vue';
export { default as MacSearchField } from './components/MacSearchField.vue';
export { default as MacGroupCard } from './components/MacGroupCard.vue';
export { default as MacSidebarItem } from './components/MacSidebarItem.vue';
export { default as MacLiquidSurface } from './components/MacLiquidSurface.vue';
export { default as MacButton } from './components/MacButton.vue';
export { default as MacAlertSheet } from './components/MacAlertSheet.vue';
export { default as MacHUD } from './components/MacHUD.vue';
export { default as MacControlCenter } from './components/MacControlCenter.vue';
export * from './tokens/colors';
export * from './tokens/materials';
export type { BadgeColor, BadgeIcon } from './components/MacIconBadge.vue';
export type { TableColumn } from './components/MacTable.vue';
export type { SegmentOption } from './components/MacSegmented.vue';
