<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue';
import { MacButton, MacSheet, MacAlertSheet } from '@sub2-mac/core';
import { getAppIcon } from '@/assets/appIcons';
import { adminUsageAPI, type AdminUsageQueryParams, type AdminUsageStatsResponse, type UsageCleanupTask, type SimpleUser, type SimpleApiKey } from '@/api/admin/usage';
import type { AdminUsageLog, TrendDataPoint, ModelStat, UserBreakdownItem, GroupStat, EndpointStat } from '@/types';
import { listErrorLogs, getErrorLogDetail, type OpsErrorLog } from '@/api/admin/ops';
import { getSnapshotV2, getModelStats, getUserBreakdown, getGroupStats, type UserBreakdownParams } from '@/api/admin/dashboard';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, ArcElement, Tooltip, Legend } from 'chart.js';
import { Line, Doughnut } from 'vue-chartjs';
import UsageBalanceHistory from './UsageBalanceHistory.vue';
import AdminFeedback from './AdminFeedback.vue';
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, ArcElement, Tooltip, Legend);
const date = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const filters=reactive<AdminUsageQueryParams>({start_date:date(new Date(Date.now()-6*86400000)),end_date:date(new Date()),model:'',sort_by:'created_at',sort_order:'desc'});
const activeTab=ref<'usage'|'errors'|'ranking'>('usage');
const errorRows=ref<OpsErrorLog[]>([]);
const detail=ref<Record<string,unknown>|null>(null),detailOpen=ref(false),detailLoading=ref(false),detailError=ref(''),detailId=ref(0);
let detailVersion=0;
const applied=ref<AdminUsageQueryParams>({...filters});
const rows=ref<AdminUsageLog[]>([]),total=ref(0),page=ref(1),pageSize=ref(25),loading=ref(false),error=ref(''),statsError=ref('');
const stats=ref<AdminUsageStatsResponse|null>(null),selected=ref<AdminUsageLog|null>(null);
const userQuery=ref(''), users=ref<SimpleUser[]>([]),keys=ref<SimpleApiKey[]>([]),searching=ref(false);
const showTasks=ref(false),tasks=ref<UsageCleanupTask[]>([]),taskPage=ref(1),taskTotal=ref(0),tasksLoading=ref(false),taskError=ref(''),busy=ref(false);
const confirmCleanup=ref(false),cancelTarget=ref<UsageCleanupTask|null>(null);
const cleanupSnapshot=ref<AdminUsageQueryParams|null>(null);
const exporting=ref(false),exportCount=ref(0),actionError=ref('');
let request:AbortController|null=null,exportRequest:AbortController|null=null,version=0,statsVersion=0,keyVersion=0,userVersion=0,taskVersion=0,disposed=false;
const pages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize.value)));
const text=(e:unknown)=>e&&typeof e==='object'&&'message' in e?String(e.message):'请求失败，请重试。';
const amount=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?`$${v.toFixed(6)}`:'—';
const state=(s:string)=>({pending:'待处理',running:'进行中',succeeded:'已完成',failed:'失败',canceled:'已取消'}[s]||s);
// Graphs use server aggregates; no aggregation of the paged usage table.
const showAnalytics=ref(true),granularity=ref<'day'|'hour'>('day');
const trend=ref<TrendDataPoint[]>([]),models=ref<ModelStat[]>([]),ranking=ref<UserBreakdownItem[]>([]);
const trendLoading=ref(false),modelLoading=ref(false),rankingLoading=ref(false);
const trendError=ref(''),modelError=ref(''),rankingError=ref('');
const modelSource=ref<'requested'|'upstream'|'mapping'>('requested'),modelMetric=ref<'total_tokens'|'actual_cost'>('total_tokens');
const rankSort=ref<NonNullable<UserBreakdownParams['sort_by']>>('total_tokens'),rankLimit=ref(50);
const rankColumns=[{key:'requests',label:'请求数'},{key:'input_tokens',label:'输入 Tokens'},{key:'output_tokens',label:'输出 Tokens'},{key:'cache_tokens',label:'缓存 Tokens'},{key:'total_tokens',label:'总 Tokens'},{key:'actual_cost',label:'用户费用'}] as const;
let trendVersion=0,modelVersion=0,rankVersion=0;
function aggregateParams(){const f=applied.value;return {start_date:f.start_date,end_date:f.end_date,user_id:f.user_id,api_key_id:f.api_key_id,account_id:f.account_id,group_id:f.group_id,model:f.model,request_type:f.request_type,stream:f.request_type==='sync'?false:f.request_type==='stream'?true:f.stream,native_compaction_v2:f.native_compaction_v2,billing_type:f.billing_type};}
function finiteFields(r:unknown,fields:string[]){return !!r&&typeof r==='object'&&fields.every(k=>typeof (r as Record<string,unknown>)[k]==='number'&&Number.isFinite((r as Record<string,unknown>)[k]));}
async function loadTrend(){const rev=++trendVersion;trendLoading.value=true;trendError.value='';trend.value=[];try{const data=await getSnapshotV2({...aggregateParams(),granularity:granularity.value,include_stats:false,include_trend:true,include_model_stats:false,include_group_stats:false,include_users_trend:false});if(disposed||rev!==trendVersion)return;if(!data||typeof data!=='object'||Array.isArray(data)||('trend' in data&&(!Array.isArray(data.trend)||!data.trend.every(r=>typeof r?.date==='string'&&finiteFields(r,['input_tokens','output_tokens','cache_creation_tokens','cache_read_tokens','total_tokens'])))))throw new Error('趋势响应不完整，请重试');trend.value=data.trend ?? [];}catch(e){if(!disposed&&rev===trendVersion)trendError.value=text(e);}finally{if(rev===trendVersion)trendLoading.value=false;}}
async function loadModels(){const rev=++modelVersion;modelLoading.value=true;modelError.value='';models.value=[];try{const data=await getModelStats({...aggregateParams(),model_source:modelSource.value});if(disposed||rev!==modelVersion)return;if(!data||!Array.isArray(data.models)||!data.models.every(r=>typeof r?.model==='string'&&finiteFields(r,['requests','total_tokens','actual_cost'])))throw new Error('模型分布响应不完整，请重试');models.value=data.models;}catch(e){if(!disposed&&rev===modelVersion)modelError.value=text(e);}finally{if(rev===modelVersion)modelLoading.value=false;}}
async function loadRanking(){const rev=++rankVersion;rankingLoading.value=true;rankingError.value='';ranking.value=[];try{const data=await getUserBreakdown({...aggregateParams(),sort_by:rankSort.value,limit:rankLimit.value});if(disposed||rev!==rankVersion)return;if(!data||!Array.isArray(data.users)||!data.users.every(r=>Number.isSafeInteger(r?.user_id)&&r.user_id>0&&typeof r.email==='string'&&finiteFields(r,['requests','input_tokens','output_tokens','cache_tokens','total_tokens','actual_cost'])))throw new Error('用户排名响应不完整，请重试');ranking.value=data.users;}catch(e){if(!disposed&&rev===rankVersion)rankingError.value=text(e);}finally{if(rev===rankVersion)rankingLoading.value=false;}}
const groups=ref<GroupStat[]>([]),groupLoading=ref(false),groupError=ref('');
const distributionMetric=ref<'total_tokens'|'actual_cost'>('total_tokens');
const endpointSource=ref<'endpoints'|'upstream_endpoints'|'endpoint_paths'>('endpoints');
const balanceUser=ref<{id:number;email:string}|null>(null);
let groupVersion=0;
const endpointRows=computed<EndpointStat[]|null>(()=>{
  const items=stats.value?.[endpointSource.value];
  return Array.isArray(items)&&items.every(r=>typeof r?.endpoint==='string'&&finiteFields(r,['requests','total_tokens','cost','actual_cost']))?items:null;
});
const distributionChart=(items:(GroupStat|EndpointStat)[])=>({labels:items.map(r=>'group_name' in r?r.group_name:r.endpoint),datasets:[{data:items.map(r=>r[distributionMetric.value]),backgroundColor:items.map((_,i)=>chartColors[i%chartColors.length])}]});
async function loadGroups(){const rev=++groupVersion;groupLoading.value=true;groupError.value='';groups.value=[];try{const {model,...params}=aggregateParams();const data=await getGroupStats(params);if(disposed||rev!==groupVersion)return;if(!Array.isArray(data?.groups)||!data.groups.every(r=>typeof r.group_name==='string'&&finiteFields(r,['group_id','requests','total_tokens','cost','actual_cost'])))throw new Error('分组分布响应不完整，请重试');groups.value=data.groups;}catch(e){if(!disposed&&rev===groupVersion)groupError.value=text(e);}finally{if(rev===groupVersion)groupLoading.value=false;}}
const breakdownTitle=ref(''),breakdownRows=ref<UserBreakdownItem[]>([]),breakdownLoading=ref(false),breakdownError=ref('');
let breakdownVersion=0;
let breakdownParams:UserBreakdownParams={};
async function loadBreakdown(){const rev=++breakdownVersion;breakdownRows.value=[];breakdownError.value='';breakdownLoading.value=true;try{const data=await getUserBreakdown(breakdownParams);if(disposed||rev!==breakdownVersion)return;if(!Array.isArray(data?.users)||!data.users.every(r=>Number.isSafeInteger(r.user_id)&&typeof r.email==='string'&&finiteFields(r,['requests','total_tokens','actual_cost'])))throw new Error('用户分布响应不完整，请重试');breakdownRows.value=data.users;}catch(e){if(!disposed&&rev===breakdownVersion)breakdownError.value=text(e);}finally{if(rev===breakdownVersion)breakdownLoading.value=false;}}
function openBreakdown(item:GroupStat|EndpointStat){const params=aggregateParams();if('group_id' in item){const {model,...rest}=params;breakdownParams={...rest,group_id:item.group_id,limit:50};breakdownTitle.value=`分组 ${item.group_name} · 用户分布`;}else{breakdownParams={...params,endpoint:item.endpoint,endpoint_type:endpointSource.value==='endpoints'?'inbound':endpointSource.value==='upstream_endpoints'?'upstream':'path',limit:50};breakdownTitle.value=`端点 ${item.endpoint} · 用户分布`;}void loadBreakdown();}
function openModelBreakdown(model:ModelStat){breakdownParams={...aggregateParams(),model:model.model,model_source:modelSource.value,limit:50};breakdownTitle.value=`模型 ${model.model} · 用户分布`;void loadBreakdown();}
function closeBreakdown(){breakdownVersion++;breakdownTitle.value='';breakdownRows.value=[];breakdownLoading.value=false;}
function openBalance(userId:number|undefined,email?:string){if(Number.isSafeInteger(userId)&&userId!>0)balanceUser.value={id:userId!,email:email||`用户 #${userId}`};}
function selectRankUser(item:UserBreakdownItem){if(!users.value.some(u=>u.id===item.user_id))users.value.push({id:item.user_id,email:item.email,deleted:false});Object.assign(filters,applied.value,{user_id:item.user_id,api_key_id:undefined});keys.value=[];keyVersion++;activeTab.value='usage';apply();}
function setRankSort(key:NonNullable<UserBreakdownParams['sort_by']>){rankSort.value=key;void loadRanking();}
function refresh(){void load();void loadStats();if(showAnalytics.value){void loadTrend();void loadModels();void loadGroups();}}
function toggleAnalytics(){showAnalytics.value=!showAnalytics.value;if(showAnalytics.value){void loadTrend();void loadModels();void loadGroups();}}
const chartColors=['#007aff','#34c759','#ff9500','#af52de','#5ac8fa','#ff2d55','#8e8e93'];
const trendChart=computed(()=>({labels:trend.value.map(r=>r.date),datasets:[{label:'输入 Tokens',data:trend.value.map(r=>r.input_tokens),borderColor:chartColors[0],backgroundColor:chartColors[0]},{label:'输出 Tokens',data:trend.value.map(r=>r.output_tokens),borderColor:chartColors[1],backgroundColor:chartColors[1]},{label:'缓存创建',data:trend.value.map(r=>r.cache_creation_tokens),borderColor:chartColors[2],backgroundColor:chartColors[2]},{label:'缓存读取',data:trend.value.map(r=>r.cache_read_tokens),borderColor:chartColors[3],backgroundColor:chartColors[3]}]}));
const modelChart=computed(()=>({labels:models.value.map(r=>r.model),datasets:[{label:modelMetric.value==='total_tokens'?'Tokens':'用户费用',data:models.value.map(r=>r[modelMetric.value]),backgroundColor:models.value.map((_,i)=>chartColors[i%chartColors.length])}]}));
const lineOptions={responsive:true,maintainAspectRatio:false,animation:false as const,plugins:{legend:{position:'bottom' as const,labels:{boxWidth:10,color:'#85858f'}}},scales:{x:{ticks:{color:'#85858f',maxTicksLimit:6},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#85858f'},grid:{color:'rgba(128,128,140,.12)'}}}};
const doughnutOptions={responsive:true,maintainAspectRatio:false,animation:false as const,plugins:{legend:{display:false}}};
const phaseOptions=[['upstream','上游'],['account_auth','账号认证'],['request','请求'],['auth','身份认证'],['routing','路由'],['internal','内部错误']];
const categoryOptions=[['auth','认证'],['rate_limit','限流'],['quota','配额'],['invalid_request','无效请求'],['service_unavailable','服务不可用'],['upstream','上游'],['internal','内部'],['cyber','安全风控']];
const filterId=`usage-filter-${Math.random().toString(36).slice(2)}`;
const showColumns=ref(false),columnError=ref('');
type Column={key:string;label:string;fixed?:boolean};
const usageColumns:Column[]=[{key:'user',label:'用户',fixed:true},{key:'api_key',label:'密钥'},{key:'account',label:'账号'},{key:'model',label:'模型'},{key:'upstream_model',label:'上游模型'},{key:'reasoning_effort',label:'推理强度'},{key:'endpoint',label:'端点'},{key:'group',label:'分组'},{key:'request_type',label:'请求类型'},{key:'billing_mode',label:'计费模式'},{key:'tokens',label:'Tokens'},{key:'actual_cost',label:'用户费用'},{key:'total_cost',label:'标准费用'},{key:'account_stats_cost',label:'账号费用'},{key:'duration_ms',label:'耗时(ms)'},{key:'created_at',label:'时间',fixed:true},{key:'request_id',label:'请求ID'},{key:'upstream_request_id',label:'上游请求ID'},{key:'user_agent',label:'User Agent'},{key:'ip_address',label:'IP地址'}];
const errorColumns:Column[]=[{key:'user',label:'用户',fixed:true},{key:'api_key',label:'密钥'},{key:'account',label:'账号'},{key:'platform',label:'平台'},{key:'model',label:'模型'},{key:'endpoint',label:'端点'},{key:'group',label:'分组'},{key:'phase',label:'阶段'},{key:'type',label:'类型'},{key:'status_code',label:'状态码',fixed:true},{key:'message',label:'消息'},{key:'created_at',label:'时间',fixed:true},{key:'user_agent',label:'User Agent'},{key:'client_ip',label:'IP地址'}];
const hiddenColumns=ref<Record<string,string[]>>({usage:['api_key','upstream_model','reasoning_effort','endpoint','group','request_type','billing_mode','total_cost','account_stats_cost','duration_ms','request_id','upstream_request_id','user_agent','ip_address'],errors:['api_key','account','platform','endpoint','group','type','user_agent','client_ip']});
const currentColumns=computed(()=>activeTab.value==='errors'?errorColumns:usageColumns);
const visibleColumns=computed(()=>currentColumns.value.filter(c=>c.fixed||!hiddenColumns.value[activeTab.value]?.includes(c.key)));
function loadColumns(){try{const raw=JSON.parse(localStorage.getItem('sub2-mac-admin-usage-columns-v1')||'null');if(!raw||typeof raw!=='object')return;for(const tab of ['usage','errors']){const defs=tab==='usage'?usageColumns:errorColumns;if(Array.isArray(raw[tab]))hiddenColumns.value[tab]=raw[tab].filter((k:unknown)=>typeof k==='string'&&defs.some(c=>c.key===k&&!c.fixed));}}catch{columnError.value='列偏好读取失败，已使用默认布局';}}
function toggleColumn(key:string){const tab=activeTab.value;if(tab==='ranking'||!currentColumns.value.some(c=>c.key===key&&!c.fixed))return;const hidden=hiddenColumns.value[tab];hiddenColumns.value[tab]=hidden.includes(key)?hidden.filter(k=>k!==key):[...hidden,key];columnError.value='';try{localStorage.setItem('sub2-mac-admin-usage-columns-v1',JSON.stringify(hiddenColumns.value));}catch{columnError.value='列设置已在本窗口生效，但未能保存到浏览器';}}
function columnValue(row:AdminUsageLog|OpsErrorLog,key:string){const r=row as unknown as Record<string,any>;if(key==='created_at')return new Date(r.created_at).toLocaleString();if(key==='user')return r.user?.email||r.user_email||`用户 #${r.user_id??'—'}`;if(key==='api_key')return r.api_key?.name||r.api_key_name||r.api_key_id||'—';if(key==='account')return r.account?.name||r.account_name||r.account_id||'—';if(key==='group')return r.group?.name||r.group_name||r.group_id||'—';if(key==='tokens')return `输入 ${r.input_tokens} / 输出 ${r.output_tokens}`;if(key==='endpoint')return r.inbound_endpoint||r.request_path||'—';if(['actual_cost','total_cost','account_stats_cost'].includes(key))return amount(r[key]);return r[key]??'—';}
function valid() {
  if(!filters.start_date||!filters.end_date||![filters.start_date,filters.end_date].every(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(new Date(d+'T00:00:00').getTime())&&date(new Date(d+'T00:00:00'))===d)||filters.start_date>filters.end_date){error.value='请选择有效的日期范围';return false;}
  for(const key of ['user_id','api_key_id','account_id','group_id'] as const) if(filters[key]!=null&&(!Number.isInteger(filters[key])||Number(filters[key])<=0)){error.value='筛选 ID 必须为正整数';return false;}
  if(activeTab.value==='errors'&&filters.status_code!=null&&(!Number.isInteger(filters.status_code)||filters.status_code<100||filters.status_code>599)){error.value='HTTP 状态码须为100–599';return false;}
  return true;
}
function paginated<T>(value: unknown, check: (item: any) => boolean): {items:T[];total:number} {
  const data=value as {items?:unknown;total?:number};
  if(!data || !Array.isArray(data.items) || !Number.isSafeInteger(data.total) || Number(data.total)<0 || data.items.length>Number(data.total) || !data.items.every(check)) throw new Error('响应格式不完整，请重新读取');
  return data as {items:T[];total:number};
}
const usageShape=(r:any)=>r&&Number.isSafeInteger(r.id)&&r.id>0&&typeof r.created_at==='string'&&typeof r.model==='string'&&Number.isFinite(r.input_tokens)&&Number.isFinite(r.output_tokens)&&Number.isFinite(r.actual_cost);
const taskShape=(r:any)=>r&&Number.isSafeInteger(r.id)&&typeof r.status==='string'&&Number.isFinite(r.deleted_rows)&&r.filters&&typeof r.filters.start_time==='string'&&typeof r.filters.end_time==='string';
function errorParams(f:AdminUsageQueryParams,p:number,size:number){return {page:p,page_size:size,view:'all' as const,start_time:f.start_date?new Date(f.start_date+'T00:00:00').toISOString():undefined,end_time:f.end_date?new Date(f.end_date+'T23:59:59.999').toISOString():undefined,user_id:f.user_id,api_key_id:f.api_key_id,account_id:f.account_id,group_id:f.group_id,model:f.model||undefined,phase:f.error_phase||undefined,category:f.error_category||undefined,status_codes:f.status_code!=null?String(f.status_code):undefined,sort_by:'created_at' as const,sort_order:f.sort_order};}
const errorShape=(r:any)=>r&&Number.isSafeInteger(r.id)&&typeof r.created_at==='string';
// Detail responses may contain complete request headers/bodies and nested API
// credentials. Display only operational fields; never stringify arbitrary DTOs.
function safeDetails(value: Record<string, unknown> | null): Record<string, unknown> {
  if (!value) return {};
  const allowed = ['id','request_id','created_at','user_id','api_key_id','account_id','group_id','model','upstream_model','platform','status_code','phase','category','error_phase','error_category','request_type','stream','billing_type','input_tokens','output_tokens','cache_creation_tokens','cache_read_tokens','total_tokens','total_cost','actual_cost','account_stats_cost','duration_ms','first_token_ms'];
  return Object.fromEntries(allowed.filter(key => ['string','number','boolean'].includes(typeof value[key])).map(key => [key,value[key]]));
}
async function openError(id:number){detailId.value=id;detailOpen.value=true;detail.value=null;detailError.value='';detailLoading.value=true;const rev=++detailVersion;try{const result=await getErrorLogDetail(id);if(disposed||rev!==detailVersion)return;if(!errorShape(result)||result.id!==id)throw new Error('错误详情响应无效');detail.value=result as unknown as Record<string,unknown>;}catch(e){if(!disposed&&rev===detailVersion)detailError.value=text(e);}finally{if(rev===detailVersion)detailLoading.value=false;}}
function switchTab(tab:'usage'|'errors'|'ranking'){if(activeTab.value===tab)return;activeTab.value=tab;error.value='';rows.value=[];errorRows.value=[];total.value=0;page.value=1;void load();void loadStats();}
async function load() {
  request?.abort();request=new AbortController();const current=request,rev=++version;
  if(activeTab.value==='ranking'){loading.value=false;await loadRanking();return;}
  loading.value=true;error.value='';
  try { if(activeTab.value==='errors'){const result=await listErrorLogs(errorParams(applied.value,page.value,pageSize.value));if(disposed||rev!==version)return;const data=paginated<OpsErrorLog>(result,errorShape);errorRows.value=data.items;total.value=data.total;if(page.value>pages.value){page.value=pages.value;void load();}return;} const result=await adminUsageAPI.list({...usageParams(applied.value),page:page.value,page_size:pageSize.value,exact_total:true},{signal:current.signal});
    if(disposed||rev!==version)return;
    const data=paginated<AdminUsageLog>(result,usageShape);rows.value=data.items;total.value=data.total;
    if(page.value>pages.value){page.value=pages.value;void load();}
  } catch(e){if(!disposed&&rev===version&&!current.signal.aborted)error.value=text(e);}
  finally{if(!disposed&&rev===version)loading.value=false;}
}
async function loadStats() {
  const rev=++statsVersion;statsError.value='';stats.value=null;if(activeTab.value!=='usage')return;
  try {const data=await adminUsageAPI.getStats({user_id:applied.value.user_id,api_key_id:applied.value.api_key_id,account_id:applied.value.account_id,group_id:applied.value.group_id,model:applied.value.model,request_type:applied.value.request_type,stream:applied.value.stream,native_compaction_v2:applied.value.native_compaction_v2,upstream_model_mismatch:applied.value.upstream_model_mismatch,start_date:applied.value.start_date,end_date:applied.value.end_date});if(!disposed&&rev===statsVersion){if(!data||!['total_requests','total_tokens','total_actual_cost','total_account_cost'].every(k=>Number.isFinite((data as unknown as Record<string,unknown>)[k])))throw new Error('统计响应格式不完整');stats.value=data;}}
  catch(e){if(!disposed&&rev===statsVersion)statsError.value=text(e);}
}
function apply(){if(!valid())return;closeBreakdown();applied.value={...filters};rows.value=[];errorRows.value=[];total.value=0;page.value=1;refresh();}
async function searchUsers(){const rev=++userVersion;searching.value=true;try{const result=await adminUsageAPI.searchUsers(userQuery.value);if(disposed||rev!==userVersion)return;if(!Array.isArray(result)||!result.every(u=>Number.isSafeInteger(u?.id)&&typeof u.email==='string'))throw new Error('用户选项响应无效');users.value=result;}catch(e){if(!disposed&&rev===userVersion)error.value=text(e);}finally{if(rev===userVersion)searching.value=false;}}
async function selectUser(){const rev=++keyVersion,id=filters.user_id;filters.api_key_id=undefined;keys.value=[];apply();try{const result=await adminUsageAPI.searchApiKeys(id);if(disposed||rev!==keyVersion||id!==filters.user_id)return;if(!Array.isArray(result)||!result.every(k=>Number.isSafeInteger(k?.id)&&typeof k.name==='string'))throw new Error('密钥选项响应无效');keys.value=result;}catch(e){if(!disposed&&rev===keyVersion)error.value=text(e);}}
function cell(v:unknown){let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+@-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function cancelExport(){exportRequest?.abort();}
function usageParams(f:AdminUsageQueryParams){const {error_phase,error_category,status_code,...params}=f;return params;}
async function exportCSV(){
  if(exporting.value||activeTab.value!=='usage')return;exporting.value=true;exportCount.value=0;error.value='';const controller=new AbortController();exportRequest=controller;
  try {
    const snapshot=usageParams({...applied.value});const all:AdminUsageLog[]=[],seen=new Set<number>();let expected=Infinity,p=1;
    while(all.length<expected){
      if(disposed||controller.signal.aborted)return;
      const res=await adminUsageAPI.list({...snapshot,page:p,page_size:100,exact_total:true},{signal:controller.signal});
      if(disposed||controller.signal.aborted)return;
      const data=paginated<AdminUsageLog>(res,usageShape);
      if(p===1)expected=data.total;else if(data.total!==expected)throw new Error('导出期间记录总数发生变化，请重新导出');
      const previous=all.length;for(const item of data.items){if(seen.has(item.id))throw new Error('导出分页包含重复记录，请重新导出');seen.add(item.id);all.push(item);}
      if(all.length>expected)throw new Error('导出数量与总数不一致，请重新导出');
      if(all.length===previous&&all.length<expected)throw new Error('导出不完整，已停止生成文件，请重试');
      exportCount.value=all.length;p++;
    }
    if(disposed||controller.signal.aborted)return;
    const content=[['ID','时间','用户','密钥','账号','分组','模型','上游模型','输入Tokens','输出Tokens','标准费用','用户费用','账号费用'],...all.map(r=>[r.id,r.created_at,r.user_id,r.api_key_id,r.account_id,r.group_id,r.model,r.upstream_model,r.input_tokens,r.output_tokens,r.total_cost,r.actual_cost,r.account_stats_cost])].map(r=>r.map(cell).join(',')).join('\r\n');
    const url=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`admin-usage-${snapshot.start_date}-${snapshot.end_date}.csv`;a.click();URL.revokeObjectURL(url);
  }catch(e){if(!disposed&&!controller.signal.aborted)error.value=text(e);}finally{if(exportRequest===controller){exporting.value=false;exportRequest=null;}}
}
async function loadTasks(){const rev=++taskVersion;tasksLoading.value=true;taskError.value='';try{const result=await adminUsageAPI.listCleanupTasks({page:taskPage.value,page_size:20});if(!disposed&&rev===taskVersion){const res=paginated<UsageCleanupTask>(result,taskShape);tasks.value=res.items;taskTotal.value=res.total;const last=Math.max(1,Math.ceil(res.total/20));if(taskPage.value>last){taskPage.value=last;void loadTasks();}}}catch(e){if(!disposed&&rev===taskVersion)taskError.value=text(e);}finally{if(rev===taskVersion)tasksLoading.value=false;}}
const cleanupDescription=computed(()=>{const f=cleanupSnapshot.value;if(!f)return '';const scope=[f.user_id!=null?`用户 #${f.user_id}`:'全部用户',f.api_key_id!=null?`密钥 #${f.api_key_id}`:'全部密钥',f.account_id!=null?`账号 #${f.account_id}`:'全部账号',f.group_id!=null?`分组 #${f.group_id}`:'全部分组',f.model?`模型 ${f.model}`:'全部模型',f.request_type?`类型 ${f.request_type}`:'全部请求类型'];return `永久删除 ${f.start_date} 至 ${f.end_date}（${Intl.DateTimeFormat().resolvedOptions().timeZone}）的用量。${scope.join('；')}。不可恢复。`;});
function prepareCleanup(){if(busy.value||activeTab.value!=='usage')return;actionError.value='';cleanupSnapshot.value={...applied.value};confirmCleanup.value=true;}
async function createCleanup(){
  if(busy.value||!confirmCleanup.value||!cleanupSnapshot.value)return;busy.value=true;actionError.value='';
  try{const f=cleanupSnapshot.value;const result=await adminUsageAPI.createCleanupTask({start_date:f.start_date!,end_date:f.end_date!,user_id:f.user_id,api_key_id:f.api_key_id,account_id:f.account_id,group_id:f.group_id,model:f.model,request_type:f.request_type,stream:f.stream,billing_type:f.billing_type,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});if(!taskShape(result))throw new Error('任务已提交但结果无法确认，请关闭确认框并刷新任务，避免重复创建');if(disposed)return;confirmCleanup.value=false;taskPage.value=1;await loadTasks();}
  catch(e){if(!disposed)actionError.value=text(e);}finally{busy.value=false;}
}
function prepareCancel(task:UsageCleanupTask){if(busy.value)return;actionError.value='';cancelTarget.value=task;}
async function cancelTask(){if(!cancelTarget.value||busy.value)return;const id=cancelTarget.value.id;busy.value=true;actionError.value='';try{const result=await adminUsageAPI.cancelCleanupTask(id);if(result?.id!==id||typeof result.status!=='string')throw new Error('取消结果无法确认，请刷新任务');if(disposed)return;cancelTarget.value=null;await loadTasks();}catch(e){if(!disposed)actionError.value=text(e);}finally{busy.value=false;}}
onMounted(()=>{loadColumns();apply();});onUnmounted(()=>{disposed=true;version++;statsVersion++;keyVersion++;userVersion++;taskVersion++;detailVersion++;trendVersion++;modelVersion++;rankVersion++;groupVersion++;breakdownVersion++;request?.abort();exportRequest?.abort();});
</script>
<template>
  <div class="admin-polish admin-usage-app flex flex-col h-full">
    <div class="admin-toolbar"><div class="flex items-center gap-3"><img :src="getAppIcon('activity')" alt=""/><div><h1>全站用量</h1><p>跨用户、密钥及上游账号的调用记录</p></div></div><div class="flex items-center gap-2"><MacButton :disabled="activeTab!=='usage'" :loading="exporting" @click="exportCSV">{{ exporting ? `已读取 ${exportCount} 条` : '导出全部 CSV' }}</MacButton><MacButton v-if="exporting" @click="cancelExport">取消导出</MacButton><MacButton @click="showTasks=true;loadTasks()">清理任务</MacButton><MacButton :loading="loading" @click="refresh">刷新</MacButton></div></div>
    <div class="flex gap-2 px-4 py-2"><MacButton :variant="activeTab==='usage'?'primary':'default'" @click="switchTab('usage')">调用用量</MacButton><MacButton :variant="activeTab==='errors'?'primary':'default'" @click="switchTab('errors')">错误请求</MacButton><MacButton :variant="activeTab==='ranking'?'primary':'default'" @click="switchTab('ranking')">用户排名</MacButton></div>
    <div class="usage-view-tools"><MacButton @click="toggleAnalytics">{{ showAnalytics?'收起图表':'展开图表' }}</MacButton><MacButton v-if="activeTab!=='ranking'" @click="showColumns=true">显示列…</MacButton><p v-if="columnError" role="alert">{{ columnError }}</p></div>
    <section v-if="showAnalytics" class="usage-analytics" aria-label="用量图表">
      <article><header><h2>Token 用量趋势</h2><label>粒度<select v-model="granularity" @change="loadTrend"><option value="day">按日</option><option value="hour">按小时</option></select></label><MacButton :loading="trendLoading" @click="loadTrend">刷新</MacButton></header><p v-if="trendLoading" role="status">正在读取趋势…</p><p v-else-if="trendError" role="alert">{{ trendError }}</p><div v-else-if="trend.length" class="usage-chart"><Line :data="trendChart" :options="lineOptions" aria-label="Token 用量趋势" role="img" /></div><p v-else>该范围暂无趋势数据</p></article>
      <article><header><h2>模型分布</h2><label>来源<select v-model="modelSource" @change="loadModels"><option value="requested">请求模型</option><option value="upstream">上游模型</option><option value="mapping">映射模型</option></select></label><label>指标<select v-model="modelMetric"><option value="total_tokens">Tokens</option><option value="actual_cost">用户费用</option></select></label><MacButton :loading="modelLoading" @click="loadModels">刷新</MacButton></header><p v-if="modelLoading" role="status">正在读取模型分布…</p><p v-else-if="modelError" role="alert">{{ modelError }}</p><div v-else-if="models.length" class="usage-models"><div class="usage-chart"><Doughnut :data="modelChart" :options="doughnutOptions" aria-label="模型用量分布" role="img" /></div><ul><li v-for="(m,index) in models" :key="m.model"><span :style="{color:chartColors[index%chartColors.length]}">●</span> <MacButton @click="openModelBreakdown(m)">{{ m.model }}</MacButton> <strong>{{ modelMetric==='actual_cost'?amount(m.actual_cost):m.total_tokens.toLocaleString() }}</strong></li></ul></div><p v-else>该范围暂无模型数据</p></article>
      <article><header><h2>分组分布</h2><label>指标<select v-model="distributionMetric"><option value="total_tokens">Tokens</option><option value="actual_cost">用户费用</option></select></label><MacButton :loading="groupLoading" @click="loadGroups">刷新分组</MacButton></header><p v-if="applied.model">分组统计不支持模型筛选，展示其余筛选条件下的分组。</p><p v-if="groupLoading" role="status">正在读取分组…</p><p v-else-if="groupError" role="alert">{{ groupError }}</p><template v-else-if="groups.length"><div class="usage-chart"><Doughnut :data="distributionChart(groups)" :options="doughnutOptions" aria-label="分组用量分布" /></div><table class="admin-table"><thead><tr><th>分组</th><th>请求 / Tokens</th><th>用户 / 标准费用</th></tr></thead><tbody><tr v-for="g in groups" :key="g.group_id"><td><MacButton @click="openBreakdown(g)">{{ g.group_name }}</MacButton></td><td>{{ g.requests }} / {{ g.total_tokens }}</td><td>{{ amount(g.actual_cost) }} / {{ amount(g.cost) }}</td></tr></tbody></table></template><p v-else>该范围暂无分组数据</p></article>
      <article v-if="activeTab==='usage'"><header><h2>端点分布</h2><label>端点来源<select aria-label="端点来源" v-model="endpointSource"><option value="endpoints">入站端点</option><option value="upstream_endpoints">上游端点</option><option value="endpoint_paths">请求路径</option></select></label><MacButton @click="loadStats">刷新端点</MacButton></header><p v-if="statsError" role="alert">{{ statsError }}</p><p v-else-if="endpointRows===null" role="status">当前统计未提供有效的端点分布。</p><template v-else-if="endpointRows.length"><div class="usage-chart"><Doughnut :data="distributionChart(endpointRows)" :options="doughnutOptions" aria-label="端点用量分布" /></div><table class="admin-table"><thead><tr><th>端点</th><th>请求 / Tokens</th><th>用户 / 标准费用</th></tr></thead><tbody><tr v-for="e in endpointRows" :key="e.endpoint"><td><MacButton @click="openBreakdown(e)">{{ e.endpoint }}</MacButton></td><td>{{ e.requests }} / {{ e.total_tokens }}</td><td>{{ amount(e.actual_cost) }} / {{ amount(e.cost) }}</td></tr></tbody></table></template><p v-else>该范围暂无端点数据</p></article>
      <p class="analytics-scope">图表按已应用的用量筛选统计；错误阶段、类别及 HTTP 状态码不影响用量图表。</p>
    </section>
    <form class="admin-filters" @submit.prevent="apply">
      <label>开始<input v-model="filters.start_date" type="date" /></label><label>结束<input v-model="filters.end_date" type="date" /></label>
      <label>查找用户<input v-model="userQuery" placeholder="邮箱关键词" /></label><MacButton :loading="searching" @click="searchUsers">搜索用户</MacButton>
      <label>用户<select v-model="filters.user_id" @change="selectUser"><option :value="undefined">全部用户</option><option v-for="u in users" :key="u.id" :value="u.id">{{ u.email }}</option></select></label>
      <label>密钥<select v-model="filters.api_key_id"><option :value="undefined">全部密钥</option><option v-for="k in keys" :key="k.id" :value="k.id">{{ k.name }}</option></select></label>
      <label>账号ID<input v-model.number="filters.account_id" type="number" min="1" @change="filters.account_id=filters.account_id||undefined" /></label><label>分组ID<input v-model.number="filters.group_id" type="number" min="1" @change="filters.group_id=filters.group_id||undefined" /></label>
      <label>模型<input v-model="filters.model" placeholder="模型名称" /></label>
      <label v-if="activeTab==='usage'">请求类型<select v-model="filters.request_type"><option :value="undefined">全部类型</option><option value="sync">非流式</option><option value="stream">流式</option><option value="ws_v2">WebSocket</option><option value="live">实时</option></select></label>
      <template v-if="activeTab==='errors'"><label>错误阶段<input v-model="filters.error_phase" :list="filterId+'-phase'" placeholder="全部阶段或输入值" /><datalist :id="filterId+'-phase'"><option v-for="option in phaseOptions" :key="option[0]" :value="option[0]">{{ option[1] }}</option></datalist></label><label>错误类别<input v-model="filters.error_category" :list="filterId+'-category'" placeholder="全部类别或输入值" /><datalist :id="filterId+'-category'"><option v-for="option in categoryOptions" :key="option[0]" :value="option[0]">{{ option[1] }}</option></datalist></label><label>HTTP 状态码<input v-model.number="filters.status_code" type="number" min="100" max="599" @change="filters.status_code=filters.status_code||undefined" /></label></template>
      <MacButton variant="primary" @click="apply">应用筛选</MacButton>
    </form>
    <AdminFeedback :loading="loading" :error="error" @retry="load" />
    <div v-if="activeTab==='usage'" class="usage-metrics"><span>请求 <strong>{{ stats?.total_requests ?? '—' }}</strong></span><span>Tokens <strong>{{ stats?.total_tokens ?? '—' }}</strong></span><span>用户费用 <strong>{{ amount(stats?.total_actual_cost) }}</strong></span><span>账号费用 <strong>{{ amount(stats?.total_account_cost) }}</strong></span></div>
    <p v-if="statsError" role="alert" class="px-4 text-xs">统计读取失败：{{ statsError }}</p>
    <div v-if="activeTab!=='ranking'" class="admin-table-scroll"><table class="admin-table"><thead><tr><th v-for="col in visibleColumns" :key="col.key">{{ col.label }}</th><th>详情</th></tr></thead><tbody><tr v-for="row in activeTab==='usage'?rows:errorRows" :key="row.id"><td v-for="col in visibleColumns" :key="col.key"><template v-if="col.key==='user'"><span>{{ columnValue(row,col.key) }}</span> <MacButton v-if="row.user_id" :aria-label="`查看用户 ${row.user_id} 余额历史`" @click="openBalance(row.user_id)">余额历史</MacButton></template><template v-else>{{ columnValue(row,col.key) }}</template></td><td><MacButton :aria-label="`查看记录 ${row.id}`" @click="activeTab==='errors'?openError(row.id):selected=row as AdminUsageLog">查看</MacButton></td></tr><tr v-if="!(activeTab==='usage'?rows:errorRows).length&&!loading"><td :colspan="visibleColumns.length+1">{{ error?'读取失败，请重试':'没有匹配的记录' }}</td></tr></tbody></table></div>
    <section v-else class="usage-ranking"><header><span>后端按所选指标降序排列；选择用户可查看其用量。</span><label>排名数量<select v-model="rankLimit" @change="loadRanking"><option v-for="n in [20,50,100,200]" :key="n" :value="n">Top {{ n }}</option></select></label><MacButton :loading="rankingLoading" @click="loadRanking">刷新排名</MacButton></header><p v-if="rankingLoading" role="status">正在读取排名…</p><p v-else-if="rankingError" role="alert">{{ rankingError }}</p><table v-else class="admin-table"><thead><tr><th>排名</th><th>用户</th><th v-for="col in rankColumns" :key="col.key" :aria-sort="rankSort===col.key?'descending':'none'"><button type="button" @click="setRankSort(col.key)">{{ col.label }} {{ rankSort===col.key?'↓':'' }}</button></th></tr></thead><tbody><tr v-for="(item,index) in ranking" :key="item.user_id"><td>{{ index+1 }}</td><td><button type="button" @click="selectRankUser(item)">{{ item.email || `用户 #${item.user_id}` }}</button> <MacButton @click="openBalance(item.user_id,item.email)">余额历史</MacButton></td><td v-for="col in rankColumns" :key="col.key">{{ col.key==='actual_cost'?amount(item.actual_cost):item[col.key].toLocaleString() }}</td></tr><tr v-if="!ranking.length"><td colspan="8">该范围暂无用户排名</td></tr></tbody></table></section>
    <MacSheet :show="showColumns" title="显示列" @close="showColumns=false"><p class="mb-3 text-xs">用量与错误请求分别保存列偏好。用户、时间、错误状态和详情始终可见。</p><div class="usage-column-picker"><label v-for="col in currentColumns" :key="col.key"><input type="checkbox" :checked="col.fixed || !hiddenColumns[activeTab]?.includes(col.key)" :disabled="col.fixed" @change="toggleColumn(col.key)" />{{ col.label }}</label></div><p v-if="columnError" role="alert">{{ columnError }}</p><template #footer><MacButton variant="primary" @click="showColumns=false">完成</MacButton></template></MacSheet>
    <MacSheet :show="detailOpen" title="错误请求详情" @close="detailOpen=false;detailVersion++"><p v-if="detailLoading" role="status">正在读取…</p><p v-if="detailError" role="alert">{{ detailError }} <MacButton @click="openError(detailId)">重试</MacButton></p><dl v-if="detail" class="usage-details"><template v-for="(value,key) in safeDetails(detail)" :key="key"><dt>{{ key }}</dt><dd>{{ typeof value==='object'?JSON.stringify(value):value??'—' }}</dd></template></dl></MacSheet>
    <MacSheet :show="!!breakdownTitle" :title="breakdownTitle" @close="closeBreakdown"><p>当前统计条件下的前 50 名用户（按用户费用排序）。</p><p v-if="breakdownLoading" role="status">正在读取用户分布…</p><p v-else-if="breakdownError" role="alert">{{ breakdownError }}</p><table v-else class="usage-breakdown"><thead><tr><th>用户</th><th>请求 / Tokens</th><th>用户费用</th></tr></thead><tbody><tr v-for="u in breakdownRows" :key="u.user_id"><td>{{ u.email }} <MacButton @click="openBalance(u.user_id,u.email)">余额历史</MacButton></td><td>{{ u.requests }} / {{ u.total_tokens }}</td><td>{{ amount(u.actual_cost) }}</td></tr></tbody></table><p v-if="!breakdownLoading&&!breakdownError&&!breakdownRows.length">暂无用户记录</p><template #footer><MacButton :loading="breakdownLoading" @click="loadBreakdown">重试 / 刷新</MacButton><MacButton @click="closeBreakdown">关闭</MacButton></template></MacSheet>
    <UsageBalanceHistory :user="balanceUser" @close="balanceUser=null" />
    <footer v-if="activeTab!=='ranking'" class="admin-footer"><span>共 {{ total }} 条</span><div class="flex gap-2"><select v-model="pageSize" aria-label="每页条数" @change="page=1;load()"><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select><MacButton :disabled="loading||page<=1" @click="page--;load()">上一页</MacButton><span>{{ page }} / {{ pages }}</span><MacButton :disabled="loading||page>=pages" @click="page++;load()">下一页</MacButton></div></footer>
    <MacSheet :show="selected!==null" title="用量详情" @close="selected=null"><dl v-if="selected" class="usage-details"><template v-for="(value,key) in safeDetails(selected as unknown as Record<string,unknown>)" :key="key"><dt>{{ key }}</dt><dd>{{ typeof value==='object'?JSON.stringify(value):value??'—' }}</dd></template></dl></MacSheet>
    <MacSheet :show="showTasks" title="用量清理任务" :loading="busy" @close="showTasks=false"><p class="text-xs mb-3">仅清理调用用量，不删除错误请求。清理范围使用已应用的用量筛选。删除无法恢复，请先导出备份。</p><p role="alert" v-if="taskError">{{ taskError }}</p><div class="flex gap-2 mb-3"><MacButton @click="loadTasks">刷新任务</MacButton><MacButton variant="destructive" :disabled="activeTab!=='usage'" @click="prepareCleanup">新建清理任务</MacButton></div><p v-if="tasksLoading" role="status">正在读取任务…</p><p v-else-if="!taskError&&!tasks.length">暂无清理任务</p><div v-for="task in tasks" :key="task.id" class="usage-task"><strong>#{{ task.id }} · {{ state(task.status) }}</strong><p>已删除 {{ task.deleted_rows }} 条 · {{ task.filters.start_time }} 至 {{ task.filters.end_time }}</p><p v-if="task.error_message">{{ task.error_message }}</p><MacButton v-if="['pending','running'].includes(task.status)" @click="prepareCancel(task)">取消任务</MacButton></div><div class="flex gap-2"><MacButton :disabled="tasksLoading||taskPage<=1" @click="taskPage--;loadTasks()">上一页</MacButton><span>{{ taskPage }}</span><MacButton :disabled="tasksLoading||taskPage*20>=taskTotal" @click="taskPage++;loadTasks()">下一页</MacButton></div></MacSheet>
    <MacAlertSheet :show="confirmCleanup" title="确认永久清理用量记录" :message="cleanupDescription" confirm-text="确认清理" danger :loading="busy" @confirm="createCleanup" @cancel="confirmCleanup=false"><p v-if="actionError" role="alert">{{ actionError }}</p></MacAlertSheet>
    <MacAlertSheet :show="cancelTarget!==null" title="取消清理任务" message="已删除的记录不会恢复，取消只停止后续清理。" confirm-text="取消任务" danger :loading="busy" @confirm="cancelTask" @cancel="cancelTarget=null"><p v-if="actionError" role="alert">{{ actionError }}</p></MacAlertSheet>
  </div>
</template>
<style scoped>
.admin-usage-app{min-width:0;position:relative;overflow:hidden}.admin-filters label{display:grid;gap:4px;font-size:11px;color:var(--text-secondary)}.admin-filters input,.admin-filters select{max-width:155px;padding:4px 7px}.usage-metrics{display:flex;gap:24px;flex-wrap:wrap;padding:12px 18px;font-size:12px;border-bottom:1px solid var(--border-subtle)}.usage-metrics strong{font-variant-numeric:tabular-nums}small{display:block;color:var(--text-secondary);margin-top:4px}.usage-details{display:grid;grid-template-columns:140px minmax(0,1fr);gap:10px;font-size:12px}.usage-details dd{overflow-wrap:anywhere;user-select:text}.usage-details dt{color:var(--text-secondary)}.usage-task{padding:12px 0;border-top:1px solid var(--border-subtle);font-size:12px;line-height:1.6}
.usage-breakdown{width:100%;font-size:12px;overflow-wrap:anywhere}.usage-breakdown td,.usage-breakdown th{padding:8px;text-align:left}.usage-view-tools{display:flex;align-items:center;gap:8px;padding:8px 16px;flex-wrap:wrap;font-size:12px}.usage-analytics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;padding:12px 16px;flex:0 0 auto;max-height:340px;overflow:auto;border-bottom:1px solid var(--border-subtle)}.usage-analytics article{min-width:0;overflow:auto}.usage-analytics .admin-table{min-width:0;font-size:11px}.usage-analytics .admin-table th,.usage-analytics .admin-table td{padding:6px;overflow-wrap:anywhere}.usage-analytics header,.usage-ranking header{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-size:12px;margin-bottom:10px}.usage-analytics h2{font-size:13px;font-weight:600;margin-right:auto}.usage-analytics label,.usage-ranking label{display:flex;gap:6px;align-items:center}.usage-analytics select,.usage-ranking select{padding:4px;border:1px solid var(--border-subtle);border-radius:6px;background:var(--bg-surface)}.usage-chart{position:relative;height:190px;min-width:0}.usage-models{display:grid;grid-template-columns:minmax(100px,1fr) minmax(100px,1fr);gap:10px}.usage-models ul{max-height:190px;overflow:auto;font-size:11px;overflow-wrap:anywhere}.usage-models li{padding:4px 0}.usage-models strong{display:block;font-variant-numeric:tabular-nums}.analytics-scope{grid-column:1/-1;font-size:11px;color:var(--text-secondary)}.usage-ranking{flex:1;min-height:0;overflow:auto;padding:12px 16px}.usage-column-picker{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;font-size:12px}.usage-column-picker label{display:flex;gap:8px;align-items:center}.admin-table td{max-width:320px;overflow-wrap:anywhere}.usage-analytics p,.usage-ranking p{font-size:12px}.usage-analytics [role=alert],.usage-ranking [role=alert]{color:var(--status-danger,#c43731)}@container app-window (max-width:700px){.admin-usage-app .admin-filters{max-height:180px;overflow:auto;flex-shrink:0}.admin-usage-app .admin-table-scroll{min-height:130px}.admin-usage-app .usage-analytics{max-height:220px}.admin-usage-app{overflow:auto}.usage-analytics{grid-template-columns:1fr;max-height:300px}.usage-chart{height:170px}}
</style>
