const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const req=require('node:module').createRequire(path.resolve(__dirname,'../packages/sub2-console/package.json'));
const vue=req('vue'),pinia=req('pinia'),ts=req('typescript'),{parse,compileTemplate}=req('vue/compiler-sfc');
const src=path.resolve(__dirname,'../packages/sub2-console/src');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};}
function compile(source){return ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;}
function helper(){const exports={};vm.runInNewContext(compile(fs.readFileSync(path.join(src,'utils/cardShop.ts'),'utf8')),{exports,URL});return exports;}
const h=helper();
test('only adapted HTTPS store URLs embed; unknown stores use neutral external mode',()=>{
 for(const url of ['https://catfk.com/shop/jianshang','https://www.16688.com.cn/shop/S790246'])assert.equal(h.supportsShopEmbed(url),true);
 for(const url of ['https://catfk.com.evil.test/shop/x','https://evil.catfk.com/shop/x','https://wzyp.cn/shop/woai','http://catfk.com/shop/x','https://catfk.com/admin','https://catfk.com:8443/shop/x'])assert.equal(h.supportsShopEmbed(url),false);
 const f=shopApp();assert.equal(f.timers.length,0);assert.match(f.s.restriction.value,/外部浏览器/);f.unmounted.forEach(fn=>fn());
});
test('shop menu IDs enforce the official 32-character limit',()=>{const draft={id:h.CARD_SHOP_PREFIX+'x'.repeat(32-h.CARD_SHOP_PREFIX.length),name:'Shop',url:'https://wzyp.cn/shop/woai'};assert.equal(h.validateShopDrafts([draft]).length,1);assert.throws(()=>h.validateShopDrafts([{...draft,id:draft.id+'x'}]));});
const owned=(id='1',extra={})=>({id:h.CARD_SHOP_PREFIX+id,label:'Example shop',url:'https://shop.example.test/buy',visibility:'user',icon_svg:h.CARD_SHOP_ICON,sort_order:0,...extra});
const menu=items=>({custom_menu_items:items});
function stripImports(source){const ast=ts.createSourceFile('test.ts',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);const names=ast.statements.flatMap(n=>ts.isVariableStatement(n)?n.declarationList.declarations.filter(d=>ts.isIdentifier(d.name)).map(d=>d.name.text):ts.isFunctionDeclaration(n)&&n.name?[n.name.text]:[]);for(const n of [...ast.statements].reverse())if(ts.isImportDeclaration(n))source=source.slice(0,n.pos)+source.slice(n.end);return {source,names};}
function component(relative,overrides={}){const filename=path.join(src,relative);const parsed=parse(fs.readFileSync(filename,'utf8'),{filename});assert.deepEqual(parsed.errors,[]);assert.deepEqual(compileTemplate({source:parsed.descriptor.template.content,filename,id:relative}).errors,[]);const {source,names}=stripImports(parsed.descriptor.scriptSetup.content);const mounted=[],unmounted=[];const c={...vue,...h,URL,crypto:require('node:crypto').webcrypto,window:{location:{protocol:'https:',origin:'https://console.example.test'}},defineProps:()=>({}),onMounted:f=>mounted.push(f),onUnmounted:f=>unmounted.push(f),setTimeout:()=>1,clearTimeout:()=>{},exports:{},...overrides};vm.createContext(c);vm.runInContext(compile(source+'\nglobalThis.subject={'+names.join(',')+'};'),c);return {s:c.subject,c,mounted,unmounted};}
function publicStore(getSettings){const auth=vue.reactive({token:'first',user:{id:1,role:'user'}});const {source}=stripImports(fs.readFileSync(path.join(src,'stores/cardShop.ts'),'utf8'));const c={...vue,...h,...pinia,exports:{},getPublicSettings:getSettings,useAuthStore:()=>auth};vm.createContext(c);vm.runInContext(compile(source),c);const instance=pinia.createPinia();return {store:c.exports.useCardShopStore(instance),auth};}
function panel(items=[owned()]){const auth=vue.reactive({token:'admin',user:{id:1,role:'admin'},isAdmin:true});let current=items;const writes=[],calls=[];const publicState=vue.reactive({error:'',reload:async()=>{calls.push('reload')}});const api={get:async()=>menu(current),update:async p=>{writes.push(p);current=p.custom_menu_items;return menu(current)}};const f=component('apps/user/settings/CardShopSettingsPanel.vue',{useAuthStore:()=>auth,useCardShopStore:()=>publicState,getSettings:()=>api.get(),updateSettings:p=>api.update(p)});return {...f,auth,writes,calls,api,publicState,setItems:x=>{current=x}};}
function shopApp(shops=[{id:'sub2mac-shop-1',name:'Example',url:'https://shop.example.test/',domain:'shop.example.test'}]){const opens=[],timers=[];const store=vue.reactive({shops,loaded:true,loading:false,error:'',load:async()=>{},reload:async()=>{}});const f=component('apps/user/CardShopApp.vue',{useCardShopStore:()=>store,useWindowManager:()=>({openApp:id=>opens.push(id)}),setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout:()=>{}});return {...f,store,opens,timers};}

test('URL accepts HTTP(S) and normalizes hostname',()=>{assert.equal(h.safeShopURL(' https://SHOP.example.test '),'https://shop.example.test/');assert.equal(h.safeShopURL('http://shop.example.test/buy'),'http://shop.example.test/buy')});
for(const url of ['javascript:alert(1)','data:text/html,bad','//shop.example.test','https://user:pass@shop.example.test','https://@shop.example.test','https://shop.example.test/a\nb','https://shop.example.test/a b','https:\\shop.example.test'])test('URL rejects unsafe '+JSON.stringify(url),()=>assert.throws(()=>h.safeShopURL(url)));
test('only user-visible reserved entries become shops',()=>{const result=h.configuredShops(menu([{id:'other',label:'Other',url:'https://other.test/',visibility:'user'},owned(),owned('admin',{visibility:'admin'})]));assert.equal(result.length,1);assert.equal(result[0].name,'Example shop');assert.equal(result[0].domain,'shop.example.test')});
test('unknown settings does not become empty successful configuration',()=>{for(const x of [null,{},menu(null),menu([null])])assert.throws(()=>h.configuredShops(x));assert.equal(h.configuredShops(menu([])).length,0)});
test('invalid owned entry and duplicates are rejected',()=>{assert.throws(()=>h.configuredShops(menu([owned('1',{url:'javascript:bad'})])));assert.throws(()=>h.validateShopDrafts([{id:'other',name:'x',url:'https://x.test'}]));assert.throws(()=>h.configuredShops(menu([owned(),owned()])))});
test('merge preserves unrelated unknown fields and most recent content',()=>{const base=[owned()];const unrelated={id:'other',label:'changed elsewhere',visibility:'admin',extra:{keep:true},icon_svg:'unchanged',url:'https://other.test'};const result=h.mergeShopItems([unrelated,...base],[{id:'sub2mac-shop-new',name:'New',url:'https://new.test'}],h.shopFingerprint(base));assert.equal(result[0],unrelated);assert.equal(result[1].visibility,'user');assert.equal(result[1].icon_svg,h.CARD_SHOP_ICON);assert.equal(result[1].label,'New')});
test('remove all shops preserves other menu items',()=>{const other={id:'untouched'};const latest=[owned(),other];const result=h.mergeShopItems(latest,[],h.shopFingerprint(latest));assert.equal(result.length,1);assert.equal(result[0],other)});
test('concurrent owned changes block merge',()=>{assert.throws(()=>h.mergeShopItems([owned('1',{label:'concurrent'})],[],h.shopFingerprint([owned()])),/其他管理员/)});
test('fingerprint ignores server JSON field ordering',()=>{const item=owned();const reverse=Object.fromEntries(Object.entries(item).reverse());assert.equal(h.shopFingerprint([item]),h.shopFingerprint([reverse]))});
test('HTTP mixed-content iframe is blocked but HTTPS remains available',()=>{assert(h.frameRestriction('http://shop.test/','https://console.example.test'));assert.equal(h.frameRestriction('https://catfk.com/shop/jianshang','https://console.example.test'),'')});
test('store publishes validated shops and loaded state',async()=>{const f=publicStore(async()=>menu([owned()]));await f.store.load();assert.equal(f.store.loaded,true);assert.equal(f.store.loading,false);assert.equal(f.store.shops.length,1);f.store.$dispose()});
test('store deduplicates normal loads and allows forced reload',async()=>{let count=0;const f=publicStore(async()=>{count++;return menu([])});await f.store.load();await f.store.load();assert.equal(count,1);await f.store.reload();assert.equal(count,2);f.store.$dispose()});
test('same-identity refresh failure retains last known shops and is retryable',async()=>{let fail=false;const f=publicStore(async()=>{if(fail)throw Error('offline');return menu([owned()])});await f.store.load();fail=true;await f.store.reload();assert.equal(f.store.loaded,true);assert.equal(f.store.shops.length,1);assert.equal(f.store.error,'offline');fail=false;await f.store.reload();assert.equal(f.store.loaded,true);f.store.$dispose()});
test('store clears synchronously on identity change and fences old response',async()=>{const first=deferred(),next=deferred();let n=0;const f=publicStore(()=>++n===1?first.promise:next.promise);const pending=f.store.load();f.auth.user={id:2,role:'user'};assert.equal(f.store.shops.length,0);assert.equal(f.store.loaded,false);next.resolve(menu([owned('new')]));await Promise.resolve();await Promise.resolve();first.resolve(menu([owned('old')]));await pending;assert.equal(f.store.shops[0].id,'sub2mac-shop-new');f.store.$dispose()});
test('disposed store rejects late response',async()=>{const a=deferred(),f=publicStore(()=>a.promise);const p=f.store.load();f.store.$dispose();a.resolve(menu([owned()]));await p;assert.equal(f.store.shops.length,0)});
test('panel only sends custom_menu_items merged from fresh settings',async()=>{const other={id:'other',label:'new remote data',custom:'preserve'};const f=panel();await f.s.load();f.s.drafts.value[0].name='Edited';f.setItems([other,owned()]);await f.s.save();assert.equal(f.writes.length,1);assert.equal(Object.keys(f.writes[0]).join(','),'custom_menu_items');assert.equal(f.writes[0].custom_menu_items[0],other);assert.equal(f.writes[0].custom_menu_items[1].label,'Edited');assert.equal(f.s.dirty.value,false);assert.equal(f.calls[0],'reload')});
test('panel blocks invalid URL before any write',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].url='javascript:alert(1)';await f.s.save();assert.equal(f.writes.length,0);assert(f.s.error.value)});
test('panel blocks own concurrent change while preserving draft',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Draft';f.setItems([owned('1',{label:'Concurrent'})]);await f.s.save();assert.equal(f.writes.length,0);assert.match(f.s.error.value,/其他管理员/);assert.equal(f.s.drafts.value[0].name,'Draft')});
test('panel multiple add/remove only mutates drafts until save',async()=>{const f=panel();await f.s.load();f.s.add();f.s.add();assert.equal(f.s.drafts.value.length,3);assert(f.s.drafts.value.every(s=>s.id.startsWith('sub2mac-shop-')));f.s.remove(f.s.drafts.value[0].id);assert.equal(f.s.drafts.value.length,2);assert.equal(f.writes.length,0)});
test('panel failed initial read stays non-writable',async()=>{const f=panel();f.api.get=async()=>({});await f.s.load();f.s.add();await f.s.save();assert.equal(f.s.loaded.value,false);assert.equal(f.writes.length,0);assert.equal(f.s.drafts.value.length,0)});
test('panel non-admin cannot load/save/add',async()=>{const f=panel();f.auth.isAdmin=false;let reads=0;f.api.get=async()=>{reads++;return menu([])};await f.s.load();f.s.add();await f.s.save();assert.equal(reads,0);assert.equal(f.writes.length,0)});
test('panel identity change during preflight prevents old-account write',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Draft';const a=deferred();f.api.get=()=>a.promise;const pending=f.s.save();f.auth.isAdmin=false;f.auth.token=null;f.auth.user=null;a.resolve(menu([owned()]));await pending;assert.equal(f.writes.length,0);assert.equal(f.s.drafts.value.length,0)});
test('panel duplicate save is fenced',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Draft';const a=deferred();let calls=0;f.api.get=()=>{calls++;return a.promise};const p=f.s.save();await f.s.save();assert.equal(calls,1);a.resolve(menu([owned()]));await p;assert.equal(f.writes.length,1)});
test('panel uncertain save response disables blind resubmission',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Draft';f.api.update=async p=>{f.writes.push(p);throw Error('response lost')};await f.s.save();await f.s.save();assert.equal(f.writes.length,1);assert.equal(f.s.loaded.value,false);assert.match(f.s.error.value,/重新读取/)});
test('panel reordered server fields do not cause false mismatch',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Draft';f.api.update=async p=>menu(p.custom_menu_items.map(item=>Object.fromEntries(Object.entries(item).reverse())));await f.s.save();assert.equal(f.s.error.value,'');assert.equal(f.s.message.value,'小铺配置已保存')});
test('app selection updates safely and identity reset clears URL',async()=>{const f=shopApp();assert.equal(f.s.selected.value.domain,'shop.example.test');f.store.shops=[];assert.equal(f.s.selected.value,null);assert.equal(f.s.selectedId.value,'');f.unmounted.forEach(fn=>fn())});
test('iframe load is unverified, not payment success; timeout remains fallback',()=>{const f=shopApp([{id:'sub2mac-shop-1',name:'Cloud',url:'https://catfk.com/shop/jianshang',domain:'catfk.com'}]);f.s.frameLoaded();assert.equal(f.s.frameStatus.value,'unverified');f.s.reloadFrame();f.timers.at(-1)();assert.equal(f.s.frameStatus.value,'slow');f.s.frameFailed();assert.equal(f.s.frameStatus.value,'error');f.unmounted.forEach(fn=>fn())});
test('app template has safe external link, constrained sandbox and voucher closure',()=>{const text=fs.readFileSync(path.join(src,'apps/user/CardShopApp.vue'),'utf8');assert.match(text,/sandbox="allow-scripts allow-forms allow-same-origin allow-popups allow-popups-to-escape-sandbox"/);assert.doesNotMatch(text,/allow-top-navigation|postMessage|localStorage|auth_token/);assert.match(text,/target="_blank" rel="noopener noreferrer"/);assert.match(text,/referrerpolicy="no-referrer"/);assert.match(text,/wm\?\.openApp\('voucher'\)/);assert.match(text,/v-else disabled>外部打开/)});

test('same-identity pending refresh preserves app registration and shop object',async()=>{let next;const f=publicStore(async()=>next?next.promise:menu([owned()]));await f.store.load();const previous=f.store.shops[0];const lengths=[];const stop=vue.watch(()=>f.store.shops.length,n=>lengths.push(n),{flush:'sync'});next=deferred();const p=f.store.reload();assert.equal(f.store.shops.length,1);assert.equal(f.store.shops[0],previous);assert.equal(f.store.loaded,true);assert.equal(f.store.loading,true);next.resolve(menu([owned()]));await p;assert.equal(lengths.includes(0),false);stop();f.store.$dispose()});
test('same-identity token rotation neither clears nor reloads shops',async()=>{let count=0;const f=publicStore(async()=>{count++;return menu([owned()])});await f.store.load();const previous=f.store.shops[0];f.auth.token='rotated-token';await vue.nextTick();assert.equal(f.store.shops[0],previous);assert.equal(f.store.loaded,true);assert.equal(count,1);f.store.$dispose()});
test('only confirmed empty refresh removes same-identity configured shops',async()=>{let next;const f=publicStore(async()=>next?next.promise:menu([owned()]));await f.store.load();next=deferred();const p=f.store.reload();assert.equal(f.store.shops.length,1);next.resolve(menu([]));await p;assert.equal(f.store.loaded,true);assert.equal(f.store.shops.length,0);assert.equal(f.store.error,'');f.store.$dispose()});
test('role change clears shops immediately even when user id is unchanged',async()=>{let next;const f=publicStore(async()=>next?next.promise:menu([owned()]));await f.store.load();next=deferred();f.auth.user.role='admin';assert.equal(f.store.shops.length,0);assert.equal(f.store.loaded,false);next.resolve(menu([owned('new-role')]));await new Promise(setImmediate);assert.equal(f.store.shops[0].id,'sub2mac-shop-new-role');f.store.$dispose()});

test('same-origin shops are external only, including canonical default ports',()=>{assert.match(h.frameRestriction('https://console.example.test/buy','https://console.example.test'),/相同来源/);assert.match(h.frameRestriction('https://console.example.test:443/buy','https://console.example.test'),/相同来源/);assert(h.frameRestriction('https://shop.example.test/buy','https://console.example.test'));assert(h.frameRestriction('https://console.example.test:8443/buy','https://console.example.test'))});
test('app gates same-origin iframe but preserves selected external URL',()=>{const f=shopApp([{id:'sub2mac-shop-1',name:'Same origin',url:'https://console.example.test/shop',domain:'console.example.test'}]);assert.match(f.s.restriction.value,/相同来源/);assert.equal(f.s.selected.value.url,'https://console.example.test/shop');assert.equal(f.timers.length,0);f.unmounted.forEach(fn=>fn())});
test('cross-origin sandbox enables storage and user popup compatibility without top navigation',()=>{const text=fs.readFileSync(path.join(src,'apps/user/CardShopApp.vue'),'utf8');const value=text.match(/sandbox="([^"]+)"/)[1].split(' ');assert(value.includes('allow-same-origin'));assert(value.includes('allow-popups-to-escape-sandbox'));assert.equal(value.some(p=>p.startsWith('allow-top-navigation')),false);assert.match(text,/iframe v-if="!restriction"/)});
test('same user profile object refresh does not clear shops',async()=>{let count=0;const f=publicStore(async()=>{count++;return menu([owned()])});await f.store.load();const previous=f.store.shops[0];f.auth.user={id:1,role:'user',balance:100};await vue.nextTick();assert.equal(f.store.shops[0],previous);assert.equal(count,1);f.store.$dispose()});
test('unchanged shop reload preserves current iframe instance',async()=>{const f=shopApp();const before=f.s.frameKey.value;f.store.shops=f.store.shops.map(shop=>({...shop}));await vue.nextTick();assert.equal(f.s.frameKey.value,before);f.store.shops=f.store.shops.map(shop=>({...shop,url:'https://shop.example.test/new'}));await vue.nextTick();assert.equal(f.s.frameKey.value,before+1);f.unmounted.forEach(fn=>fn())});
test('panel token and same-user profile refresh retain unsaved draft',async()=>{const f=panel();await f.s.load();f.s.drafts.value[0].name='Unsaved';f.auth.token='rotated';f.auth.user={id:1,role:'admin',balance:5};await vue.nextTick();assert.equal(f.s.drafts.value[0].name,'Unsaved');assert.equal(f.s.dirty.value,true)});
