const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const req=require('node:module').createRequire(path.resolve(__dirname,'../packages/sub2-console/package.json'));
const chartJS=req('chart.js');
const vue=req('vue'),ts=req('typescript'),{parse,compileTemplate}=req('vue/compiler-sfc');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};}
const row=id=>({id,created_at:'2026-09-11T00:00:00Z',model:'test',input_tokens:1,output_tokens:2,actual_cost:0.1});
const task={id:1,status:'pending',deleted_rows:0,filters:{start_time:'a',end_time:'b'}};
function fixture(name,overrides={}){
 const filename=path.resolve(__dirname,'../packages/sub2-console/src/apps/admin/'+name+'.vue');const d=parse(fs.readFileSync(filename,'utf8')).descriptor;
 assert.equal(compileTemplate({source:d.template.content,filename,id:name}).errors.length,0);
 let source=d.scriptSetup.content;const ast=ts.createSourceFile('x.ts',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
 const chartBindings={};
 for(const statement of ast.statements){
  if(!ts.isImportDeclaration(statement)||statement.moduleSpecifier.text!=='chart.js')continue;
  const bindings=statement.importClause?.namedBindings;
  assert(bindings&&ts.isNamedImports(bindings),'Chart.js imports must be explicit named bindings');
  for(const entry of bindings.elements){const imported=entry.propertyName?.text||entry.name.text;assert(chartJS[imported],`Missing real Chart.js export: ${imported}`);chartBindings[entry.name.text]=chartJS[imported];}
 }
 const names=ast.statements.flatMap(n=>ts.isVariableStatement(n)?n.declarationList.declarations.filter(d=>ts.isIdentifier(d.name)).map(d=>d.name.text):ts.isFunctionDeclaration(n)&&n.name?[n.name.text]:[]);
 for(const n of [...ast.statements].reverse())if(ts.isImportDeclaration(n))source=source.slice(0,n.pos)+source.slice(n.end);
 const downloads=[],events=[],unmount=[];const props=vue.reactive({item:null,user:null});
 const api={getUsages:async()=>({items:[],total:0}),update:async(id,p)=>({id,...p}),deleteCode:async()=>({message:'ok'})};
 const usage={list:async()=>({items:[],total:0}),getStats:async()=>({total_requests:0,total_tokens:0,total_actual_cost:0,total_account_cost:0}),searchUsers:async()=>[],searchApiKeys:async()=>[],listCleanupTasks:async()=>({items:[],total:0}),createCleanupTask:async()=>task,cancelCleanupTask:async id=>({id,status:'canceled'})};
 const c={...vue,...chartBindings,useWindowManager:()=>undefined,getById:async id=>({id,email:'fixture',balance:0,created_at:'2026-09-01T00:00:00Z'}),localStorage:{getItem:()=>null,setItem:()=>{}},getSnapshotV2:async()=>({trend:[]}),getModelStats:async()=>({models:[]}),getGroupStats:async()=>({groups:[]}),getUserBalanceHistory:async()=>({items:[],total:0,total_recharged:0}),getUserBreakdown:async()=>({users:[]}),AbortController,Date,Intl,Blob,console,adminUsageAPI:usage,api,defineProps:()=>props,defineEmits:()=>e=>events.push(e),onMounted:()=>{},onUnmounted:f=>unmount.push(f),listErrorLogs:async()=>({items:[],total:0}),getErrorLogDetail:async id=>({id,created_at:'now'}),URL:{createObjectURL:b=>{downloads.push(b);return 'blob:test'},revokeObjectURL:()=>{}},document:{createElement:()=>({click(){}})},...overrides};vm.createContext(c);vm.runInContext(ts.transpile(source+'\nglobalThis.subject={'+names.join(',')+'}',{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}),c);return {s:c.subject,c,usage,api,props,events,downloads,unmount};
}
async function promo(){const f=fixture('PromoInspector');f.props.item={id:7,code:'CODE',bonus_amount:1,max_uses:5,status:'active',notes:'',expires_at:'2027-01-01T12:34:56Z'};await vue.nextTick();await Promise.resolve();return f;}
test('usage rejects malformed list and retains safe state',async()=>{const f=fixture('AdminUsageApp');f.usage.list=async()=>({items:null,total:3});await f.s.load();assert(f.s.error.value);assert.equal(f.s.rows.value.length,0)});
test('usage ignores late list response',async()=>{const f=fixture('AdminUsageApp'),a=deferred();let n=0;f.usage.list=()=>++n===1?a.promise:Promise.resolve({items:[row(2)],total:1});const first=f.s.load();await f.s.load();a.resolve({items:[row(1)],total:1});await first;assert.equal(f.s.rows.value[0].id,2)});
test('stats invalid response clears old metrics',async()=>{const f=fixture('AdminUsageApp');await f.s.loadStats();f.usage.getStats=async()=>null;await f.s.loadStats();assert.equal(f.s.stats.value,null);assert(f.s.statsError.value)});
test('stats ignores late response',async()=>{const f=fixture('AdminUsageApp'),a=deferred();let n=0;f.usage.getStats=()=>++n===1?a.promise:Promise.resolve({total_requests:2,total_tokens:0,total_actual_cost:0,total_account_cost:0});const p=f.s.loadStats();await f.s.loadStats();a.resolve({total_requests:1,total_tokens:0,total_actual_cost:0,total_account_cost:0});await p;assert.equal(f.s.stats.value.total_requests,2)});
test('key search ignores previous user response',async()=>{const f=fixture('AdminUsageApp'),a=deferred();f.usage.searchApiKeys=id=>id===1?a.promise:Promise.resolve([{id:2,name:'new'}]);f.s.filters.user_id=1;const p=f.s.selectUser();f.s.filters.user_id=2;await f.s.selectUser();a.resolve([{id:1,name:'old'}]);await p;assert.equal(f.s.keys.value[0].id,2)});
test('CSV exports all 205 rows and exact filter snapshot',async()=>{const f=fixture('AdminUsageApp'),calls=[];f.usage.list=async p=>{calls.push(p);return {items:Array.from({length:Math.min(100,205-(p.page-1)*100)},(_,i)=>row((p.page-1)*100+i+1)),total:205}};await f.s.exportCSV();assert.deepEqual(calls.map(x=>x.page),[1,2,3]);assert.equal(f.downloads.length,1);assert.equal((await f.downloads[0].text()).split('\r\n').length,206)});
for(const mode of ['duplicate','empty','changed','shape'])test('CSV rejects '+mode+' pagination',async()=>{const f=fixture('AdminUsageApp');f.usage.list=async p=>p.page===1?{items:[row(1)],total:2}:mode==='shape'?{items:null,total:2}:{items:mode==='empty'?[]:[row(mode==='duplicate'?1:2)],total:mode==='changed'?3:2};await f.s.exportCSV();assert.equal(f.downloads.length,0);assert(f.s.error.value)});
test('CSV canceled in-flight does not continue or download',async()=>{const f=fixture('AdminUsageApp'),a=deferred();let n=0;f.usage.list=()=>{n++;return a.promise};const p=f.s.exportCSV();f.s.cancelExport();a.resolve({items:[row(1)],total:2});await p;assert.equal(n,1);assert.equal(f.downloads.length,0);assert.equal(f.s.exporting.value,false)});
test('CSV quotes commas/newlines and guards whitespace formulas',()=>{const f=fixture('AdminUsageApp');for(const x of ['=1',' +1','\t@x','\r-2'])assert(f.s.cell(x).startsWith('"\''));assert.equal(f.s.cell('a,"b"'),'"a,""b"""')});
test('cleanup requires confirmation and uses frozen applied filters',async()=>{const f=fixture('AdminUsageApp');let payload;f.usage.createCleanupTask=async p=>{payload=p;return task};await f.s.createCleanup();assert.equal(payload,undefined);f.s.applied.value.user_id=7;f.s.prepareCleanup();f.s.applied.value.user_id=9;await f.s.createCleanup();assert.equal(payload.user_id,7);assert.equal(f.s.confirmCleanup.value,false)});
test('cleanup failure remains visible inside confirmation state',async()=>{const f=fixture('AdminUsageApp');f.usage.createCleanupTask=async()=>{throw Error('denied')};f.s.prepareCleanup();await f.s.createCleanup();assert.equal(f.s.actionError.value,'denied');assert.equal(f.s.confirmCleanup.value,true)});
test('cancel failure retains target and visible error',async()=>{const f=fixture('AdminUsageApp');f.usage.cancelCleanupTask=async()=>{throw Error('denied')};f.s.prepareCancel(task);await f.s.cancelTask();assert.equal(f.s.actionError.value,'denied');assert.equal(f.s.cancelTarget.value.id,1)});
test('task malformed filters handled without rendering unsafe row',async()=>{const f=fixture('AdminUsageApp');f.usage.listCleanupTasks=async()=>({items:[{id:1}],total:1});await f.s.loadTasks();assert(f.s.taskError.value);assert.equal(f.s.tasks.value.length,0)});
test('error query uses official names and local day boundaries',()=>{const f=fixture('AdminUsageApp');const p=f.s.errorParams({start_date:'2026-09-11',end_date:'2026-09-12',status_code:429,error_phase:'upstream',error_category:'rate_limit',model:'m'},2,25);assert.equal(p.status_codes,'429');assert.equal(p.phase,'upstream');assert.equal(p.category,'rate_limit');assert.equal(p.view,'all');assert.equal(p.start_time,new Date('2026-09-11T00:00:00').toISOString());assert.equal(p.end_time,new Date('2026-09-12T23:59:59.999').toISOString())});
test('errors do not query usage statistics or create cleanup',async()=>{const f=fixture('AdminUsageApp');f.s.activeTab.value='errors';f.usage.getStats=async()=>{throw Error('wrong endpoint')};await f.s.loadStats();f.s.prepareCleanup();await f.s.exportCSV();assert.equal(f.s.confirmCleanup.value,false);assert.equal(f.s.statsError.value,'');assert.equal(f.downloads.length,0)});
test('error list late response cannot replace usage results',async()=>{const a=deferred(),f=fixture('AdminUsageApp',{listErrorLogs:()=>a.promise});f.s.activeTab.value='errors';const p=f.s.load();f.s.activeTab.value='usage';await f.s.load();a.resolve({items:[{id:1,created_at:'now'}],total:1});await p;assert.equal(f.s.errorRows.value.length,0)});
test('error detail failure visible and retryable',async()=>{const f=fixture('AdminUsageApp',{getErrorLogDetail:async()=>{throw Error('detail failed')}});await f.s.openError(1);assert.equal(f.s.detailError.value,'detail failed');assert.equal(f.s.detailOpen.value,true)});
test('promo unchanged expiration omitted to preserve precision',async()=>{const f=await promo();let p;f.api.update=async(id,x)=>{p=x;return {id,code:'CODE'}};await f.s.save();assert.equal(Object.hasOwn(p,'expires_at'),false);assert(f.events.includes('updated'))});
test('promo clearing expiration sends official zero',async()=>{const f=await promo();let p;f.api.update=async(id,x)=>{p=x;return {id,code:'CODE'}};f.s.expiry.value='';await f.s.save();assert.equal(p.expires_at,0)});
test('promo edited expiration sends unix seconds',async()=>{const f=await promo();let p;f.api.update=async(id,x)=>{p=x;return {id,code:'CODE'}};f.s.expiry.value='2027-03-01T09:20:30';await f.s.save();assert.equal(p.expires_at,Math.floor(new Date('2027-03-01T09:20:30').getTime()/1000))});
test('promo invalid status prevents mutation',async()=>{const f=await promo();f.s.draft.value.status='unknown';await f.s.save();assert.equal(f.events.length,0);assert(f.s.error.value)});
test('promo late history page ignored',async()=>{const f=await promo(),a=deferred();f.api.getUsages=async(id,p)=>p===1?a.promise:{items:[{id:2,user_id:1,used_at:'now',bonus_amount:1}],total:40};const first=f.s.loadHistory();f.s.page.value=2;await f.s.loadHistory();a.resolve({items:[{id:1,user_id:1,used_at:'now',bonus_amount:1}],total:40});await first;assert.equal(f.s.history.value[0].id,2)});
test('promo malformed history explicit error',async()=>{const f=await promo();f.api.getUsages=async()=>({items:null,total:2});await f.s.loadHistory();assert(f.s.historyError.value)});
test('promo delete requires confirmation and failure remains on alert',async()=>{const f=await promo();let count=0;f.api.deleteCode=async()=>{count++;throw Error('delete denied')};await f.s.remove();assert.equal(count,0);f.s.prepareDelete();await f.s.remove();assert.equal(count,1);assert.equal(f.s.deleteError.value,'delete denied');assert.equal(f.s.deleting.value,true)});
test('promo stale save cannot close newly selected item',async()=>{const f=await promo(),a=deferred();f.api.update=()=>a.promise;const p=f.s.save();f.props.item={...f.props.item,id:8};await vue.nextTick();a.resolve({id:7,code:'CODE'});await p;assert.equal(f.events.length,0)});
test('usage calendar overflow rejected',()=>{const f=fixture('AdminUsageApp');f.s.filters.start_date='2026-02-30';f.s.filters.end_date='2026-03-02';assert.equal(f.s.valid(),false)});
test('usage endpoint omits error-only filters',()=>{const f=fixture('AdminUsageApp');const p=f.s.usageParams({model:'m',error_phase:'auth',error_category:'auth',status_code:401});assert.equal(p.model,'m');assert.equal(Object.hasOwn(p,'error_phase'),false);assert.equal(Object.hasOwn(p,'status_code'),false)});
test('promo invalid calendar date rejected',async()=>{const f=await promo();f.s.expiry.value='2027-02-30T09:20:30';await f.s.save();assert.equal(f.events.length,0);assert(f.s.error.value)});
test('unmounted usage ignores in-flight list',async()=>{const f=fixture('AdminUsageApp'),a=deferred();f.usage.list=()=>a.promise;const p=f.s.load();f.unmount.forEach(fn=>fn());a.resolve({items:[row(1)],total:1});await p;assert.equal(f.s.rows.value.length,0)});
const trendRow={date:'2026-09-12',input_tokens:10,output_tokens:5,cache_creation_tokens:2,cache_read_tokens:3,total_tokens:20};
const modelRow={model:'model',requests:2,total_tokens:20,actual_cost:0.2};
const rankRow={user_id:9,email:'rank@example.test',requests:2,input_tokens:10,output_tokens:5,cache_tokens:5,total_tokens:20,actual_cost:0.2};
test('trend uses official snapshot flags and applied filter snapshot',async()=>{let sent;const f=fixture('AdminUsageApp',{getSnapshotV2:async p=>{sent=p;return {trend:[trendRow]}}});f.s.applied.value.user_id=8;f.s.filters.user_id=99;f.s.applied.value.request_type='stream';f.s.granularity.value='hour';await f.s.loadTrend();assert.equal(sent.user_id,8);assert.equal(sent.stream,true);assert.equal(sent.granularity,'hour');assert.equal(sent.include_trend,true);assert.equal(sent.include_stats,false);assert.equal(sent.include_model_stats,false);assert.equal(f.s.trendChart.value.datasets[0].data[0],10)});
test('trend rejects malformed response and clears stale graph',async()=>{const f=fixture('AdminUsageApp',{getSnapshotV2:async()=>({trend:null})});f.s.trend.value=[trendRow];await f.s.loadTrend();assert.equal(f.s.trend.value.length,0);assert(f.s.trendError.value)});
test('trend newer request wins without fake aggregate',async()=>{const a=deferred();let count=0;const f=fixture('AdminUsageApp',{getSnapshotV2:()=>++count===1?a.promise:Promise.resolve({trend:[{...trendRow,input_tokens:999}]})});const old=f.s.loadTrend();await f.s.loadTrend();a.resolve({trend:[trendRow]});await old;assert.equal(f.s.trend.value[0].input_tokens,999)});
test('model distribution sends all official sources and uses server values',async()=>{const sent=[];const f=fixture('AdminUsageApp',{getModelStats:async p=>{sent.push(p);return {models:[modelRow]}}});for(const source of ['requested','upstream','mapping']){f.s.modelSource.value=source;await f.s.loadModels();}assert.deepEqual(sent.map(p=>p.model_source),['requested','upstream','mapping']);f.s.modelMetric.value='actual_cost';assert.equal(f.s.modelChart.value.datasets[0].data[0],0.2);f.s.modelMetric.value='total_tokens';assert.equal(f.s.modelChart.value.datasets[0].data[0],20)});
test('model source late response ignored',async()=>{const a=deferred();let count=0;const f=fixture('AdminUsageApp',{getModelStats:()=>++count===1?a.promise:Promise.resolve({models:[{...modelRow,model:'new'}]})});const old=f.s.loadModels();f.s.modelSource.value='mapping';await f.s.loadModels();a.resolve({models:[modelRow]});await old;assert.equal(f.s.models.value[0].model,'new')});
test('model malformed metric shows error and retry succeeds',async()=>{let count=0;const f=fixture('AdminUsageApp',{getModelStats:async()=>++count===1?{models:[{...modelRow,actual_cost:'fake'}]}:{models:[modelRow]}});await f.s.loadModels();assert(f.s.modelError.value);await f.s.loadModels();assert.equal(f.s.modelError.value,'');assert.equal(f.s.models.value.length,1)});
test('ranking sends backend sort and top limit without client sorting',async()=>{let sent;const f=fixture('AdminUsageApp',{getUserBreakdown:async p=>{sent=p;return {users:[rankRow,{...rankRow,user_id:10,total_tokens:200}]}}});f.s.rankSort.value='actual_cost';f.s.rankLimit.value=200;f.s.applied.value.group_id=3;await f.s.loadRanking();assert.equal(sent.sort_by,'actual_cost');assert.equal(sent.limit,200);assert.equal(sent.group_id,3);assert.equal(f.s.ranking.value[0].user_id,9)});
test('ranking sorting race ignored',async()=>{const a=deferred();let n=0;const f=fixture('AdminUsageApp',{getUserBreakdown:()=>++n===1?a.promise:Promise.resolve({users:[{...rankRow,user_id:10}]})});const p=f.s.loadRanking();f.s.rankSort.value='requests';await f.s.loadRanking();a.resolve({users:[rankRow]});await p;assert.equal(f.s.ranking.value[0].user_id,10)});
test('ranking malformed response produces visible failure',async()=>{const f=fixture('AdminUsageApp',{getUserBreakdown:async()=>({users:[{user_id:1}]})});await f.s.loadRanking();assert(f.s.rankingError.value);assert.equal(f.s.ranking.value.length,0)});
test('ranking user drilldown applies user and clears incompatible key',async()=>{const f=fixture('AdminUsageApp');f.s.activeTab.value='ranking';f.s.applied.value.api_key_id=7;f.s.selectRankUser(rankRow);assert.equal(f.s.activeTab.value,'usage');assert.equal(f.s.applied.value.user_id,9);assert.equal(f.s.applied.value.api_key_id,undefined);assert.equal(f.s.users.value[0].email,'rank@example.test')});
test('columns fixed fields cannot hide; optional fields persist per tab',()=>{const saved=[];const f=fixture('AdminUsageApp',{localStorage:{getItem:()=>null,setItem:(k,v)=>saved.push([k,JSON.parse(v)])}});f.s.toggleColumn('user');assert.equal(saved.length,0);f.s.toggleColumn('model');assert(f.s.hiddenColumns.value.usage.includes('model'));assert.equal(f.s.hiddenColumns.value.errors.includes('model'),false);assert.equal(saved[0][1].usage.includes('model'),true);assert.equal(f.s.visibleColumns.value.some(c=>c.key==='model'),false)});
test('columns restore whitelist rejects unknown and fixed hidden values',()=>{const f=fixture('AdminUsageApp',{localStorage:{getItem:()=>JSON.stringify({usage:['user','model','bogus'],errors:['created_at','message']}),setItem(){}}});f.s.loadColumns();assert.equal(f.s.hiddenColumns.value.usage.join(','),'model');assert.equal(f.s.hiddenColumns.value.errors.join(','),'message')});
test('column storage failure does not undo local choice',()=>{const f=fixture('AdminUsageApp',{localStorage:{getItem:()=>'{broken',setItem:()=>{throw Error('denied')}}});f.s.loadColumns();assert(f.s.columnError.value);f.s.toggleColumn('model');assert(f.s.hiddenColumns.value.usage.includes('model'));assert(f.s.columnError.value)});
test('official phase/category suggestions retain unknown query input',()=>{const f=fixture('AdminUsageApp');assert.equal(f.s.phaseOptions.map(x=>x[0]).join(','),'upstream,account_auth,request,auth,routing,internal');assert.equal(f.s.categoryOptions.map(x=>x[0]).join(','),'auth,rate_limit,quota,invalid_request,service_unavailable,upstream,internal,cyber');const p=f.s.errorParams({error_phase:'future_phase',error_category:'future_category'},1,25);assert.equal(p.phase,'future_phase');assert.equal(p.category,'future_category')});
test('unmount fences aggregate responses',async()=>{const a=deferred(),b=deferred(),c=deferred();const f=fixture('AdminUsageApp',{getSnapshotV2:()=>a.promise,getModelStats:()=>b.promise,getUserBreakdown:()=>c.promise});const pending=[f.s.loadTrend(),f.s.loadModels(),f.s.loadRanking()];f.unmount.forEach(fn=>fn());a.resolve({trend:[trendRow]});b.resolve({models:[modelRow]});c.resolve({users:[rankRow]});await Promise.all(pending);assert.equal(f.s.trend.value.length+f.s.models.value.length+f.s.ranking.value.length,0)});

test('VM injects actual Chart.js import aliases and registers real chart components',()=>{const f=fixture('AdminUsageApp');assert.equal(f.c.ChartJS,chartJS.Chart);assert.equal(f.c.CategoryScale,chartJS.CategoryScale);assert.equal(chartJS.Chart.registry.getScale('category'),chartJS.CategoryScale);assert.equal(chartJS.Chart.registry.getScale('linear'),chartJS.LinearScale);for(const key of ['point','line','arc'])assert(chartJS.Chart.registry.getElement(key));for(const key of ['tooltip','legend'])assert(chartJS.Chart.registry.getPlugin(key));});

// 2026-09-12 review: payload minimization and privacy, using actual component methods.
test('promo editing only notes does not overwrite concurrent bonus/limit/status changes',async()=>{
 const f=await promo();let payload;f.api.update=async(id,p)=>{payload=p;return{id,code:'CODE'}};
 f.s.draft.value.notes='reviewed';await f.s.save();assert.deepEqual(JSON.parse(JSON.stringify(payload)),{notes:'reviewed'});
 assert(f.events.includes('updated'));
});
test('promo close clears hidden draft and history rather than retaining previous customer data',async()=>{
 const f=await promo();f.s.draft.value.notes='private-note';f.props.item=null;await vue.nextTick();
 assert.deepEqual(JSON.parse(JSON.stringify(f.s.draft.value)),{});assert.equal(f.s.history.value.length,0);assert.equal(f.s.expiry.value,'');
});
test('usage detail allowlist excludes nested keys, request secrets and arbitrary future DTO fields',()=>{
 const f=fixture('AdminUsageApp');const safe=f.s.safeDetails({id:9,model:'visible',actual_cost:0.3,api_key:{name:'key',key:'sk-secret'},request_headers:{Authorization:'Bearer secret'},request_body:'private prompt',response_body:'private output',credentials:'secret',future:'private',error_message:'authorization=secret'});
 assert.deepEqual(JSON.parse(JSON.stringify(safe)),{id:9,model:'visible',actual_cost:0.3});
 assert.deepEqual(JSON.parse(JSON.stringify(f.s.safeDetails(null))),{});
});

test('review: statistics preserve applied compaction and upstream mismatch filters',async()=>{
 const f=fixture('AdminUsageApp');let sent;f.usage.getStats=async p=>{sent=p;return{total_requests:0,total_tokens:0,total_actual_cost:0,total_account_cost:0}};
 f.s.applied.value.native_compaction_v2=true;f.s.applied.value.upstream_model_mismatch=true;await f.s.loadStats();
 assert.equal(sent.native_compaction_v2,true);assert.equal(sent.upstream_model_mismatch,true);
});

const groupFixture={group_id:7,group_name:'Group',requests:30,total_tokens:100,cost:2,actual_cost:1};
test('release group aggregate honors applied filters and omits unsupported model',async()=>{let params;const f=fixture('AdminUsageApp',{getGroupStats:async p=>{params=p;return{groups:[groupFixture]}}});f.s.applied.value.user_id=9;f.s.applied.value.model='unsupported';f.s.filters.user_id=99;await f.s.loadGroups();assert.equal(params.user_id,9);assert.equal(Object.hasOwn(params,'model'),false);assert.equal(f.s.groups.value[0].total_tokens,100);});
test('release group failures clear data, retry and fence late/unmounted responses',async()=>{const a=deferred();let n=0;const f=fixture('AdminUsageApp',{getGroupStats:()=>++n===1?a.promise:Promise.resolve({groups:[groupFixture]})});const old=f.s.loadGroups();await f.s.loadGroups();a.resolve({groups:[{...groupFixture,total_tokens:999}]});await old;assert.equal(f.s.groups.value[0].total_tokens,100);f.c.getGroupStats=async()=>({groups:[{...groupFixture,cost:null}]});await f.s.loadGroups();assert(f.s.groupError.value);assert.equal(f.s.groups.value.length,0);f.c.getGroupStats=()=>a.promise;f.unmount.forEach(fn=>fn());await f.s.loadGroups();assert.equal(f.s.groups.value.length,0);});
test('release endpoint sources distinguish unsupported, malformed, empty and zero cost',()=>{const f=fixture('AdminUsageApp');assert.equal(f.s.endpointRows.value,null);f.s.stats.value={endpoints:[],upstream_endpoints:[{endpoint:'/responses',requests:1,total_tokens:5,cost:0,actual_cost:0}],endpoint_paths:[{endpoint:'/bad',cost:0}]};assert.equal(f.s.endpointRows.value.length,0);f.s.endpointSource.value='upstream_endpoints';assert.equal(f.s.endpointRows.value[0].actual_cost,0);f.s.endpointSource.value='endpoint_paths';assert.equal(f.s.endpointRows.value,null);});
const historyItem={id:1,type:'admin_balance',value:-2,created_at:'2026-09-13',notes:'adjustment',validity_days:0};
test('release balance history is paged server data with official type filter',async()=>{const calls=[];const f=fixture('UsageBalanceHistory',{getUserBalanceHistory:async(...p)=>{calls.push(p);return{items:[historyItem],total:31,total_recharged:0}}});f.props.user={id:8,email:'fixture'};await vue.nextTick();await f.s.load();f.s.page.value=2;f.s.kind.value='admin_balance';await f.s.load();assert.equal(calls.at(-1).join(','),'8,2,15,admin_balance');assert.equal(f.s.pages.value,3);assert.equal(f.s.recharged.value,0);assert.equal(f.s.valueLabel(historyItem),'-$2.000000');assert.equal(f.s.valueLabel({...historyItem,type:'subscription',validity_days:30}),'30 天');});
test('release balance history 403 and malformed payload are not empty success',async()=>{const f=fixture('UsageBalanceHistory',{getUserBalanceHistory:async()=>{throw Error('403 管理员权限不足')}});f.props.user={id:8,email:'fixture'};await vue.nextTick();await f.s.load();assert.match(f.s.error.value,/403/);assert.equal(f.s.recharged.value,null);f.c.getUserBalanceHistory=async()=>({items:[],total:1,total_recharged:'fake'});await f.s.load();assert(f.s.error.value);f.c.getUserBalanceHistory=async()=>({items:[],total:0,total_recharged:0});await f.s.load();assert.equal(f.s.error.value,'');});
test('release balance history switching users/closing/unmount ignores old responses',async()=>{const a=deferred();const f=fixture('UsageBalanceHistory',{getUserBalanceHistory:id=>id===8?a.promise:Promise.resolve({items:[{...historyItem,id:2}],total:1,total_recharged:10})});f.props.user={id:8,email:'old'};await vue.nextTick();const old=f.s.load();f.props.user={id:9,email:'new'};await vue.nextTick();await f.s.load();a.resolve({items:[historyItem],total:1,total_recharged:99});await old;assert.equal(f.s.rows.value[0].id,2);const b=deferred();f.c.getUserBalanceHistory=()=>b.promise;const pending=f.s.load();f.s.close();b.resolve({items:[historyItem],total:1,total_recharged:99});await pending;assert.equal(f.s.rows.value.length,0);assert.equal(f.s.recharged.value,null);f.unmount.forEach(fn=>fn());await f.s.load();assert.equal(f.s.rows.value.length,0);});

test('release distribution drilldown sends official endpoint type and frozen scope',async()=>{let sent;const f=fixture('AdminUsageApp',{getUserBreakdown:async p=>{sent=p;return{users:[rankRow]}}});f.s.applied.value.user_id=8;f.s.endpointSource.value='endpoint_paths';f.s.openBreakdown({endpoint:'/path'});await Promise.resolve();assert.equal(sent.endpoint_type,'path');assert.equal(sent.endpoint,'/path');assert.equal(sent.user_id,8);assert.equal(sent.limit,50);f.s.applied.value.model='m';f.s.openBreakdown(groupFixture);await Promise.resolve();assert.equal(sent.group_id,7);assert.equal(Object.hasOwn(sent,'model'),false);});
test('release closing distribution drilldown fences pending results',async()=>{const a=deferred();const f=fixture('AdminUsageApp',{getUserBreakdown:()=>a.promise});f.s.openBreakdown(groupFixture);f.s.closeBreakdown();a.resolve({users:[rankRow]});await Promise.resolve();await Promise.resolve();assert.equal(f.s.breakdownTitle.value,'');assert.equal(f.s.breakdownRows.value.length,0);});

test('RF02 model breakdown preserves source and replaces only selected model',async()=>{let sent;const f=fixture('AdminUsageApp',{getUserBreakdown:async p=>{sent=p;return{users:[rankRow]}}});f.s.applied.value={user_id:8,group_id:7,model:'old',request_type:'stream'};for(const source of ['requested','upstream','mapping']){f.s.modelSource.value=source;f.s.openModelBreakdown({model:'selected'});await Promise.resolve();assert.equal(sent.model_source,source);assert.equal(sent.model,'selected');assert.equal(sent.user_id,8);assert.equal(sent.group_id,7);assert.equal(sent.stream,true);}});
test('RF02 profile uses include_deleted and real dated stats, not mock user usage',async()=>{const calls=[];const f=fixture('UsageBalanceHistory',{getById:async(...args)=>{calls.push(args);return{id:8,email:'real',balance:0,username:'name',created_at:'2026-09-01T00:00:00Z',notes:'note',deleted_at:'2026-09-02'}}});let params;f.usage.getStats=async p=>{params=p;return{total_actual_cost:0}};f.props.user={id:8,email:'old'};await vue.nextTick();await f.s.loadOverview();assert.equal(calls.at(-1).join(','),'8,true');assert.equal(params.user_id,8);assert.equal(params.start_date,'2026-09-01');assert(params.end_date&&params.timezone);assert.equal(f.s.overview.value.balance,0);assert.equal(f.s.overview.value.notes,'note');assert.equal(f.s.spent.value,0);});
test('RF02 profile wrong identity rejected and stats failure retains profile without fake zero',async()=>{const f=fixture('UsageBalanceHistory',{getById:async()=>({id:99,email:'wrong',balance:10,created_at:'2026-09-01'})});f.props.user={id:8,email:'fixture'};await vue.nextTick();await f.s.loadOverview();assert(f.s.overviewError.value);assert.equal(f.s.overview.value,null);f.c.getById=async()=>({id:8,email:'right',balance:10,created_at:'2026-09-01'});f.usage.getStats=async()=>{throw Error('503')};await f.s.loadOverview();assert.equal(f.s.overview.value.email,'right');assert.equal(f.s.spent.value,null);assert(f.s.spentError.value);});
test('RF02 late overview/statistics cannot leak across close or user switch',async()=>{const a=deferred();const f=fixture('UsageBalanceHistory',{getById:id=>id===8?a.promise:Promise.resolve({id,email:'new',balance:4,created_at:'2026-09-01'})});f.props.user={id:8,email:'old'};await vue.nextTick();const old=f.s.loadOverview();f.props.user={id:9,email:'new'};await vue.nextTick();await f.s.loadOverview();a.resolve({id:8,email:'old',balance:999,created_at:'2026-09-01'});await old;assert.equal(f.s.overview.value.email,'new');const b=deferred();f.usage.getStats=()=>b.promise;const pending=f.s.loadOverview();await Promise.resolve();f.s.close();b.resolve({total_actual_cost:99});await pending;assert.equal(f.s.overview.value,null);assert.equal(f.s.spent.value,null);});
test('RF02 audit opens existing audit app without misusing actor ID as target user',()=>{const calls=[];let prevented=false;const f=fixture('UsageBalanceHistory',{useWindowManager:()=>({openApp:(...args)=>calls.push(args)})});f.s.openAudit({preventDefault(){prevented=true}});assert(prevented);assert.equal(calls[0][0],'security');assert.deepEqual(JSON.parse(JSON.stringify(calls[0][1])),{tab:'audit'});assert(f.events.includes('close'));});
