const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const resolve=n=>require.resolve(n,{paths:[path.join(root,'packages/sub2-console')]});const ts=require(resolve('typescript')),vue=require(resolve('vue')),sfc=require(resolve('vue/compiler-sfc'));
function load(file,mocks={}){const source=fs.readFileSync(path.join(root,file),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const mod={exports:{}};new Function('require','module','exports',js)(n=>n==='vue'?vue:mocks[n]||{},mod,mod.exports);return mod.exports;}
const {useBatchImages,validatePayload,validateZip,groupJobs}=load('packages/sub2-console/src/apps/user/batch-image/useBatchImages.ts');
const payload=()=>({model:'gemini-2.5-flash-image',items:[{custom_id:'one',prompt:'完整\n提示词',output_count:1}]});
const key=(id=1)=>({id,key:'fixture-only-'+id,name:'fixture',status:'active',group:{platform:'gemini',allow_batch_image_generation:true}});
const job=(id='job',status='completed')=>({id,status,task_name:'测试任务',model:'gemini-2.5-flash-image',success_count:1,fail_count:1,hold_amount:1,actual_cost:1,created_at:1});
function fixture(overrides={},keyOverrides={}){const calls=[];const api={listBatchImageJobs:async(k,o)=>{calls.push(['list',k,o]);return {data:[job()],has_more:true};},listBatchImageModels:async()=>({data:[{id:payload().model}]}),getBatchImageJob:async(k,id)=>job(id),listBatchImageItems:async()=>({data:[{custom_id:'one',status:'failed',prompt_preview:'完整提示词'}],has_more:false}),submitBatchImageJob:async(k,p,id)=>{calls.push(['submit',k,p,id]);return job('new','queued');},cancelBatchImageJob:async()=>{calls.push(['cancel']);},deleteBatchImageJobRecord:async()=>{calls.push(['delete']);},downloadBatchImageZip:async()=>new Blob([new Uint8Array([80,75,3,4,0,0])],{type:'application/zip'}),saveBlob:()=>{calls.push(['save']);},...overrides};const state=useBatchImages(api,{list:async()=>({items:[key()],total:1}),...keyOverrides});state.keyId.value=1;return {state,calls};}
test('actual app SFC script/template compile',()=>{const filename=path.join(root,'packages/sub2-console/src/apps/user/BatchImageApp.vue');const {descriptor,errors}=sfc.parse(fs.readFileSync(filename,'utf8'));assert.deepEqual(errors,[]);sfc.compileScript(descriptor,{id:'batch'});assert.deepEqual(sfc.compileTemplate({source:descriptor.template.content,filename,id:'batch'}).errors,[]);});
test('reference and output limits preserve multiline prompt',()=>{assert.equal(validatePayload(payload()),1);const p=payload();p.items[0].output_count=5;assert.throws(()=>validatePayload(p),/1–4/);p.items=Array.from({length:51},(_,i)=>({custom_id:String(i),prompt:'p',output_count:4}));assert.throws(()=>validatePayload(p),/200/);p.items=[{custom_id:'a',prompt:'p',reference_images:Array.from({length:4},()=>({mime_type:'image/png',data:'YQ=='}))}];assert.throws(()=>validatePayload(p),/3张/);});
test('duplicates, blank prompts and invalid image sources rejected',()=>{let p=payload();p.items.push({...p.items[0]});assert.throws(()=>validatePayload(p),/唯一/);p=payload();p.items[0].prompt=' ';assert.throws(()=>validatePayload(p));p=payload();p.items[0].reference_images=[{mime_type:'image/png',file_uri:'https://example.invalid/a'}];assert.throws(()=>validatePayload(p),/gs:/);});
test('all key pages loaded and only eligible keys selectable',async()=>{const {state}=fixture({}, {list:async p=>p===1?{items:[{...key(),status:'inactive'}],total:2}:{items:[key(2)],total:2}});await state.loadKeys();assert.equal(state.keys.value[0].id,2);state.dispose();});
test('task paging uses numeric offset and filters reset',async()=>{const {state,calls}=fixture();await state.loadKeys();await state.turnPage(1);assert.equal(calls.filter(c=>c[0]==='list').at(-1)[2].cursor,'20');state.filters.status='failed';await state.loadJobs(true);assert.equal(state.page.value,0);assert.equal(calls.at(-1)[2].status,'failed');state.dispose();});
test('stale list response cannot replace new filter result',async()=>{let resolve;const {state}=fixture();await state.loadKeys();const {state:s}=fixture({listBatchImageJobs:async(k,o)=>o.status==='old'?new Promise(r=>resolve=r):{data:[job('new')],has_more:false}});await s.loadKeys();s.filters.status='old';const old=s.loadJobs();s.filters.status='new';await s.loadJobs();resolve({data:[job('old')],has_more:false});await old;assert.equal(s.jobs.value[0].id,'new');state.dispose();s.dispose();});
test('same failed submission retains idempotency key, success clears it',async()=>{const ids=[];let fail=true;const {state}=fixture({submitBatchImageJob:async(k,p,id)=>{ids.push(id);if(fail)throw new Error('lost response');return job('new');}});await state.loadKeys();await state.submit(payload());fail=false;await state.submit(payload());assert.equal(ids[0],ids[1]);await state.submit(payload());assert.notEqual(ids[1],ids[2]);state.dispose();});
test('concurrent submit is rejected and invalid model never reaches API',async()=>{let finish;const {state,calls}=fixture({submitBatchImageJob:()=>new Promise(r=>finish=r)});await state.loadKeys();const first=state.submit(payload());assert.equal(await state.submit(payload()),false);finish(job());await first;await state.submit({...payload(),model:'not-available'});assert.match(state.error.value,/模型/);assert.equal(calls.filter(c=>c[0]==='submit').length,0);state.dispose();});
test('running deletion and empty downloads are blocked; terminal delete works',async()=>{const {state,calls}=fixture();await state.loadKeys();await state.action('delete',job('running','running'));assert.equal(calls.some(c=>c[0]==='delete'),false);await state.action('download',{...job(),success_count:0});assert.equal(calls.some(c=>c[0]==='save'),false);await state.action('delete',job());assert.equal(calls.some(c=>c[0]==='delete'),true);state.dispose();});
test('closed detail ignores late response and incomplete retry is blocked',async()=>{let finish;const {state}=fixture({getBatchImageJob:()=>new Promise(r=>finish=r)});await state.loadKeys();const req=state.openDetail(job());state.closeDetail();finish(job());await req;assert.equal(state.detail.value,null);state.detail.value=job();state.items.value=[{custom_id:'failed',status:'failed',prompt_preview:'retry me'},{custom_id:'ok',status:'success',prompt_preview:'do not retry'}];let p=state.retryPayload();assert.equal(p.items.length,1);assert.equal(p.parent_batch_id,'job');state.itemsMore.value=true;assert.throws(()=>state.retryPayload(),/完整/);state.dispose();});
test('full upstream Agent guide retains limits, billing, recovery and endpoints',()=>{const {agentGuide}=load('packages/sub2-console/src/apps/user/batch-image/guide.ts');const g=agentGuide('https://example.invalid');for(const word of ['200','1000','128MB','batch-image-resume.json','60 到 120','Id','成功','/v1/images/batches']){if(word==='Id')continue;assert.ok(g.includes(word),word);}assert.ok(g.includes('https://example.invalid/v1/images/batches'));});
test('cancel and download call only the selected operation',async()=>{const {state,calls}=fixture();await state.loadKeys();await state.action('cancel',job('job','running'));assert.equal(calls.filter(c=>c[0]==='cancel').length,1);await state.action('download',job());assert.equal(calls.filter(c=>c[0]==='save').length,1);assert.equal(calls.filter(c=>c[0]==='delete').length,0);state.dispose();});
test('list failures preserve rows and show error',async()=>{let fail=false;const {state}=fixture({listBatchImageJobs:async()=>{if(fail)throw new Error('fixture offline');return {data:[job('kept')],has_more:false};}});await state.loadKeys();fail=true;await state.loadJobs();assert.equal(state.jobs.value[0].id,'kept');assert.equal(state.error.value,'fixture offline');state.dispose();});
test('late preview after closing detail never creates an object URL',async()=>{let finish;const {state}=fixture({getBatchImageItemContent:()=>new Promise(r=>finish=r)});await state.loadKeys();await state.openDetail(job());const request=state.preview({custom_id:'one',status:'success',image_count:2});state.closeDetail();finish(new Blob(['image']));await request;assert.deepEqual(state.previews.value,{});state.dispose();});
test('missing failed prompt blocks retry instead of silently skipping items',async()=>{const {state}=fixture();await state.loadKeys();await state.openDetail(job());state.items.value.push({custom_id:'missing',status:'failed',prompt_preview:null});assert.throws(()=>state.retryPayload(),/缺少/);state.dispose();});
test('all-key merge keeps global order across numeric pages and owner for actions',async()=>{const ownerCalls=[];const rows=Array.from({length:45},(_,i)=>({...job('a'+i),created_at:100-i}));const other=Array.from({length:25},(_,i)=>({...job('b'+i),created_at:99.5-i}));const {state}=fixture({listBatchImageJobs:async(k,o)=>{const list=k.endsWith('1')?rows:other;const offset=Number(o.cursor||0);return {data:list.slice(offset,offset+o.limit),has_more:offset+o.limit<list.length};},deleteBatchImageJobRecord:async(k,id)=>ownerCalls.push([k,id])},{list:async()=>({items:[key(1),key(2)],total:2})});state.keyId.value=null;await state.loadKeys();assert.equal(state.jobs.value[0].id,'a0');assert.equal(state.jobs.value[1].id,'b0');const first=state.jobs.value.map(j=>j.id);await state.turnPage(1);assert.equal(state.jobs.value[0].id,'a10');assert.ok(state.jobs.value.every(j=>!first.includes(j.id)));await state.action('delete',state.jobs.value.find(j=>j.id==='b10'));assert.deepEqual(ownerCalls,[['fixture-only-2','b10']]);state.dispose();});
test('complete family expansion discovers parent and child across API pages',async()=>{const root=job('root'),child={...job('child'),parent_batch_id:'root'};const rows=[root,...Array.from({length:100},(_,i)=>job('unrelated'+i)),child];const {state}=fixture({listBatchImageJobs:async(k,o)=>{const start=Number(o.cursor||0);return {data:rows.slice(start,start+o.limit),has_more:start+o.limit<rows.length};}});await state.loadKeys();await state.loadFamily(root);assert.deepEqual(state.familyJobs.value.root.map(j=>j.id),['root','child']);const f=groupJobs(state.familyJobs.value.root)[0];assert.equal(f.children.length,1);assert.equal(f.success,2);state.dispose();});
test('ZIP MIME and magic reject HTML disguised by filename or content type',async()=>{await assert.rejects(()=>validateZip(new Blob(['<html>failure</html>'],{type:'application/zip'})),/签名/);await assert.rejects(()=>validateZip(new Blob([new Uint8Array([80,75,3,4])],{type:'text/html'})),/类型/);await validateZip(new Blob([new Uint8Array([80,75,3,4,0])],{type:'application/octet-stream'}));const {state,calls}=fixture({downloadBatchImageZip:async()=>new Blob(['<html>'],{type:'text/html'})});await state.loadKeys();await state.action('download',job());assert.equal(calls.some(c=>c[0]==='save'),false);state.dispose();});
test('multimage preview forwards image index and rejects out of range',async()=>{const indexes=[];const {state}=fixture({getBatchImageItemContent:async(k,id,custom,index)=>{indexes.push(index);return new Blob(['png'],{type:'image/png'});}});await state.loadKeys();await state.openDetail(job());const item={custom_id:'multi',status:'success',image_count:3};await state.preview(item,0);await state.preview(item,2);await state.preview(item,3);assert.deepEqual(indexes,[0,2]);assert.equal(Object.keys(state.previews.value).length,2);state.dispose();});
test('GCS reference retains MIME and purpose without inline data',()=>{const p=payload();p.items[0].reference_images=[{id:'style',type:'style',mime_type:'image/png',file_uri:'gs://private-bucket/path/style.png'}];assert.equal(validatePayload(p),1);p.items[0].reference_images[0].file_uri='gs://bucket';assert.throws(()=>validatePayload(p),/gs:/);});
test('old-key task cannot fall back to a newly selected key, unknown ownership never writes',async()=>{
  const writes=[];const {state}=fixture({listBatchImageJobs:async k=>({data:[job(k.endsWith('1')?'old':'new')],has_more:false}),deleteBatchImageJobRecord:async(k,id)=>writes.push([k,id])},{list:async()=>({items:[key(1),key(2)],total:2})});
  await state.loadKeys();const old=state.jobs.value[0];state.keyId.value=2;await state.changeKey();await state.action('delete',old);await state.action('delete',job('unknown'));assert.equal(writes.length,0);assert.match(state.error.value,/所属密钥/);state.dispose();
});
test('refreshing the same key after ambiguous submit retains idempotency identifier',async()=>{
  const requests=[];const {state}=fixture({submitBatchImageJob:async(k,p,id)=>{requests.push(id);throw {message:'503 supplied by API'};}});
  await state.loadKeys();await state.submit(payload());await state.loadKeys();await state.submit(payload());assert.equal(requests[0],requests[1]);assert.match(state.error.value,/503 supplied/);state.dispose();
});
test('cancel failure returns false and retains task; success returns true',async()=>{
  let fail=true;const {state}=fixture({cancelBatchImageJob:async()=>{if(fail)throw {message:'cancel failed'};}});await state.loadKeys();assert.equal(await state.action('cancel',job('job','running')),false);assert.match(state.error.value,/cancel failed/);assert.equal(state.jobs.value.length,1);fail=false;assert.equal(await state.action('cancel',job('job','running')),true);state.dispose();
});
function appFixture(overrides={}){
 const filename=path.join(root,'packages/sub2-console/src/apps/user/BatchImageApp.vue');const {descriptor}=sfc.parse(fs.readFileSync(filename,'utf8'));const source=sfc.compileScript(descriptor,{id:'review-batch'}).content;
 const state=fixture().state;const unmounted=[];const module={exports:{}};
 const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 new Function('require','module','exports',js)(id=>id==='vue'?{...vue,onMounted:()=>{},onUnmounted:fn=>unmounted.push(fn)}:id.includes('useBatchImages')?{useBatchImages:()=>state,statusLabel:v=>v,terminal:s=>s==='completed',validatePayload,groupJobs}:id.includes('appIcons')?{getAppIcon:()=>''}:id.includes('url')?{buildGatewayUrl:x=>x}:id.includes('guide')?{agentGuide:()=>''}:{},module,module.exports);
 Object.assign(state,overrides);const result=module.exports.default.setup({}, {expose:()=>{}});return {s:result,state,unmounted};
}
test('actual app confirmation remains open on failure and closes only on success',async()=>{
 let ok=false;const {s,state}=appFixture({action:async()=>ok});s.pending.value={kind:'cancel',job:job()};await s.confirm();assert.ok(s.pending.value);ok=true;await s.confirm();assert.equal(s.pending.value,null);state.dispose();
});
test('selected deletion preserves failed and unprocessed tasks for retry',async()=>{
 const {s,state}=appFixture({action:async(kind,j)=>j.id==='a'});state.jobs.value=[job('a'),job('b'),job('c')];s.selection.value=['a','b','c'];s.deletingSelected.value=true;await s.deleteSelected();assert.deepEqual(s.selection.value,['b','c']);assert.equal(s.deletingSelected.value,true);state.dispose();
});
test('download helper revokes URL and removes link even when click throws',()=>{
 const oldURL=global.URL,oldDocument=global.document;let removed=0,revoked=0;
 try{global.URL={createObjectURL:()=> 'blob:fixture',revokeObjectURL:()=>revoked++};global.document={createElement:()=>({click(){throw Error('blocked');},remove(){removed++;}}),body:{appendChild(){}}};const api=load('packages/sub2-console/src/api/batchImage.ts');assert.throws(()=>api.saveBlob(new Blob(['x']),'a.zip'),/blocked/);assert.equal(removed,1);assert.equal(revoked,1);}finally{global.URL=oldURL;global.document=oldDocument;}
});
test('batch API handles detail errors and object messages without [object Object]',async()=>{
 const original=global.fetch;try{const api=load('packages/sub2-console/src/api/batchImage.ts',{'./client':{buildGatewayUrl:p=>p}});
 for(const [body,expected] of [[{detail:'quota exceeded'},'quota exceeded'],[{message:{nested:'do not stringify'}},'HTTP 503']]){global.fetch=async()=>new Response(JSON.stringify(body),{status:503});await assert.rejects(()=>api.cancelBatchImageJob('fixture','id'),err=>err.message===expected&&err.status===503);}}finally{global.fetch=original;}
});
test('closing creation aborts pending file reader, drops drafts and never appends stale references',async()=>{
 const original=global.FileReader;let reader,aborted=0;
 try{global.FileReader=class{constructor(){reader=this;}readAsDataURL(){}abort(){aborted++;this.onabort?.();}};
 const {s,state}=appFixture();s.creating.value=true;s.rows.value=[{custom_id:'a',prompt:'private draft'}];const reading=s.addImages({target:{files:[{size:1,type:'image/png'}],value:'selected'}});s.closeCreate();await reading;assert.equal(aborted,1);assert.equal(s.rows.value.length,0);assert.equal(s.references.value.length,0);assert.equal(s.referenceBusy.value,false);assert.equal(reader.onload,null);state.dispose();}finally{global.FileReader=original;}
});
